### ISSUE TITLE
It crashed when I export monobehaviour

### ISSUE THREAD

**Issue by mskgroup** [nesrak1/UABEA#107]
Application: UABEAvalonia.exe
CoreCLR Version: 5.0.921.35908
.NET Version: 5.0.9
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException: Non-negative number required. (Parameter 'count')
   at System.IO.BinaryReader.ReadBytes(Int32 count)
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField)
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField)
   at AssetsTools.NET.AssetTypeInstance..ctor(AssetTypeTemplateField[] baseFields, AssetsFileReader reader, Int64 filePos)
   at UABEAvalonia.AssetWorkspace.GetConcatMonoBaseField(AssetContainer cont, String managedPath) in D:\a\UABEA\UABEA\UABEAvalonia\AssetWorkspace.cs:line 221
   at UABEAvalonia.InfoWindow.BatchExportDump(List`1 selection) in D:\a\UABEA\UABEA\UABEAvalonia\InfoWindow.axaml.cs:line 479
   at UABEAvalonia.InfoWindow.BtnExportDump_Click(Object sender, RoutedEventArgs e) in D:\a\UABEA\UABEA\UABEAvalonia\InfoWindow.axaml.cs:line 253
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 157
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 107
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 134
   at UABEAvalonia.Program.Main(String[] args) in D:\a\UABEA\UABEA\UABEAvalonia\Program.cs:line 47

**Comment by nesrak1** [comment]
Is this not the same as #69? You can try debugging this in AssetsView to see where reading goes wrong.

**Comment by mskgroup** [comment]
> Is this not the same as #69? You can try debugging this in AssetsView to see where reading goes wrong.

They should be different, this is another game, it crashed when I export monobehaviour in batch

**Comment by nesrak1** [comment]
Closing since this issue is pretty old.
