### ISSUE TITLE
I want to unpack data.unity3d to many file.

### ISSUE THREAD

**Issue by louisome** [nesrak1/UABEA#125]
First, I select the file "data.unity3d", and then I need to Export all the files one by one.

I want to unpack it and export all the files to the disk.

Can you make a button to do this funtion for me? Thank you very much~

**Comment by nesrak1** [comment]
There's no button right now but you can do it from the command line for now.
1. Create a file like this and call it something like `batch.txt`
```
+FILE C:\path\to\bundle\data.unity3d
```
2. Run `UABEAvalonia batchexport batch.txt` from the command line.

**Comment by louisome** [comment]
When I do that, it will show me some error:

Decompressing G:\ASproject\Test\src\main\assets\bin\Data\data.unity3d...
Exporting G:\ASproject\Test\src\main\assets\bin\Data\data.unity3d_globalgamemanagers.assets...
Exporting G:\ASproject\Test\src\main\assets\bin\Data\data.unity3d_Resources/unity_builtin_extra.assets...
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path 'G:\ASproject\Test\src\main\assets\bin\Data\data.unity3d_Resources\unity_builtin_extra.assets'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes)
   at System.IO.File.WriteAllBytes(String path, Byte[] bytes)
   at UABEAvalonia.CommandLineHandler.BatchExport(String[] args) in D:\a\UABEA\UABEA\UABEAvalonia\CommandLineHandler.cs:line 171
   at UABEAvalonia.CommandLineHandler.CLHMain(String[] args) in D:\a\UABEA\UABEA\UABEAvalonia\CommandLineHandler.cs:line 376
   at UABEAvalonia.Program.Main(String[] args) in D:\a\UABEA\UABEA\UABEAvalonia\Program.cs:line 41


unity version : 2020.3.20f1

**Comment by eliteforcevn** [comment]
where i can get the batch commands?
