### ISSUE TITLE
Crash :(

### ISSUE THREAD

**Issue by karohan** [nesrak1/UABEA#146]
Hatalı uygulama adı: UABEAvalonia.exe, sürüm: 1.0.0.0, zaman damgası: 0x609308e7
Hatalı modül adı: KERNELBASE.dll, sürüm: 10.0.19041.1387, zaman damgası: 0x0b9a844a
Özel durum kodu: 0xe0434352
Hata uzaklığı 0x0000000000034f69
Hatalı işlem kimliği: 0x1742c
Uygulama başlangıç zamanı: 0x01d808af9d691fb7
Hatalı uygulama yolu: C:\Users\Karohan\Downloads\Compressed\uabea_rel3_win_x64_2\net5.0\UABEAvalonia.exe
Hatalı modül yolu: C:\Windows\System32\KERNELBASE.dll
Rapor kimliği: 9e3e5605-7944-4879-a2c1-b40aef489273
Hatalı paket tam adı: 
Hatalı paketle ilgili uygulama kimliği: 

`- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2022-01-13T18:59:19.7614236Z" /> 
  <EventRecordID>88573</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>DESKTOP-CNN3ANN</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>UABEAvalonia.exe</Data> 
  <Data>1.0.0.0</Data> 
  <Data>609308e7</Data> 
  <Data>KERNELBASE.dll</Data> 
  <Data>10.0.19041.1387</Data> 
  <Data>0b9a844a</Data> 
  <Data>e0434352</Data> 
  <Data>0000000000034f69</Data> 
  <Data>1742c</Data> 
  <Data>01d808af9d691fb7</Data> 
  <Data>C:\Users\Karohan\Downloads\Compressed\uabea_rel3_win_x64_2\net5.0\UABEAvalonia.exe</Data> 
  <Data>C:\Windows\System32\KERNELBASE.dll</Data> 
  <Data>9e3e5605-7944-4879-a2c1-b40aef489273</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>`

Günlük Adı:    Application
Kaynak:        .NET Runtime
Tarih:         13/01/2022 10:10:31 PM
Olay Kimliği:  1026
Görev Kategorisi:Yok
Düzey:         Hata
Anahtar sözcükler:Klasik
Kullanıcı:     Yok
Bilgisayar:    DESKTOP-CNN3ANN
Açıklama:
Application: UABEAvalonia.exe
CoreCLR Version: 5.0.1321.56516
.NET Version: 5.0.13
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at System.IO.BinaryReader.ReadUInt32()
   at AssetsTools.NET.AssetsFileReader.ReadUInt32() in C:\Users\nesquack\Documents\GitReposLocal\AssetsTools.NET\AssetTools.NET\Standard\AssetsFileFormat\AssetsFileReader.cs:line 54
   at AssetsTools.NET.Type_0D.Read(Boolean hasTypeTree, AssetsFileReader reader, UInt32 version) in C:\Users\nesquack\Documents\GitReposLocal\AssetsTools.NET\AssetTools.NET\Standard\AssetsFileFormat\Type_0D.cs:line 46
   at AssetsTools.NET.TypeTree.Read(AssetsFileReader reader, UInt32 version) in C:\Users\nesquack\Documents\GitReposLocal\AssetsTools.NET\AssetTools.NET\Standard\AssetsFileFormat\TypeTree.cs:line 30
   at AssetsTools.NET.AssetsFile..ctor(AssetsFileReader reader) in C:\Users\nesquack\Documents\GitReposLocal\AssetsTools.NET\AssetTools.NET\Standard\AssetsFileFormat\AssetsFile.cs:line 33
   at AssetsTools.NET.Extra.AssetsFileInstance..ctor(Stream stream, String filePath, String root) in C:\Users\nesquack\Documents\GitReposLocal\AssetsTools.NET\AssetTools.NET\Extra\AssetsManager\AssetsFileInstance.cs:line 26
   at AssetsTools.NET.Extra.AssetsManager.LoadAssetsFile(Stream stream, String path, Boolean loadDeps, String root, BundleFileInstance bunInst) in C:\Users\nesquack\Documents\GitReposLocal\AssetsTools.NET\AssetTools.NET\Extra\AssetsManager\AssetsManager.cs:line 29
   at AssetsTools.NET.Extra.AssetsManager.LoadAssetsFile(FileStream stream, Boolean loadDeps, String root) in C:\Users\nesquack\Documents\GitReposLocal\AssetsTools.NET\AssetTools.NET\Extra\AssetsManager\AssetsManager.cs:line 51
   at AssetsTools.NET.Extra.AssetsManager.LoadAssetsFile(String path, Boolean loadDeps, String root) in C:\Users\nesquack\Documents\GitReposLocal\AssetsTools.NET\AssetTools.NET\Extra\AssetsManager\AssetsManager.cs:line 56
   at UABEAvalonia.MainWindow.MenuOpen_Click(Object sender, RoutedEventArgs e) in C:\Users\nesquack\Documents\GitRepos\uabequickfixes\UABEA\UABEAvalonia\MainWindow.axaml.cs:line 138
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run() in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 166
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 208
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 157
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 107
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 134
   at UABEAvalonia.Program.Main(String[] args) in C:\Users\nesquack\Documents\GitRepos\uabequickfixes\UABEA\UABEAvalonia\Program.cs:line 47

Olay Xml'si:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-01-13T19:10:31.5530923Z" />
    <EventRecordID>88656</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-CNN3ANN</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: UABEAvalonia.exe
CoreCLR Version: 5.0.1321.56516
.NET Version: 5.0.13
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at System.IO.BinaryReader.ReadUInt32()
   at AssetsTools.NET.AssetsFileReader.ReadUInt32() in C:\Users\nesquack\Documents\GitReposLocal\AssetsTools.NET\AssetTools.NET\Standard\AssetsFileFormat\AssetsFileReader.cs:line 54
   at AssetsTools.NET.Type_0D.Read(Boolean hasTypeTree, AssetsFileReader reader, UInt32 version) in C:\Users\nesquack\Documents\GitReposLocal\AssetsTools.NET\AssetTools.NET\Standard\AssetsFileFormat\Type_0D.cs:line 46
   at AssetsTools.NET.TypeTree.Read(AssetsFileReader reader, UInt32 version) in C:\Users\nesquack\Documents\GitReposLocal\AssetsTools.NET\AssetTools.NET\Standard\AssetsFileFormat\TypeTree.cs:line 30
   at AssetsTools.NET.AssetsFile..ctor(AssetsFileReader reader) in C:\Users\nesquack\Documents\GitReposLocal\AssetsTools.NET\AssetTools.NET\Standard\AssetsFileFormat\AssetsFile.cs:line 33
   at AssetsTools.NET.Extra.AssetsFileInstance..ctor(Stream stream, String filePath, String root) in C:\Users\nesquack\Documents\GitReposLocal\AssetsTools.NET\AssetTools.NET\Extra\AssetsManager\AssetsFileInstance.cs:line 26
   at AssetsTools.NET.Extra.AssetsManager.LoadAssetsFile(Stream stream, String path, Boolean loadDeps, String root, BundleFileInstance bunInst) in C:\Users\nesquack\Documents\GitReposLocal\AssetsTools.NET\AssetTools.NET\Extra\AssetsManager\AssetsManager.cs:line 29
   at AssetsTools.NET.Extra.AssetsManager.LoadAssetsFile(FileStream stream, Boolean loadDeps, String root) in C:\Users\nesquack\Documents\GitReposLocal\AssetsTools.NET\AssetTools.NET\Extra\AssetsManager\AssetsManager.cs:line 51
   at AssetsTools.NET.Extra.AssetsManager.LoadAssetsFile(String path, Boolean loadDeps, String root) in C:\Users\nesquack\Documents\GitReposLocal\AssetsTools.NET\AssetTools.NET\Extra\AssetsManager\AssetsManager.cs:line 56
   at UABEAvalonia.MainWindow.MenuOpen_Click(Object sender, RoutedEventArgs e) in C:\Users\nesquack\Documents\GitRepos\uabequickfixes\UABEA\UABEAvalonia\MainWindow.axaml.cs:line 138
   at System.Threading.Tasks.Task.&lt;&gt;c.&lt;ThrowAsync&gt;b__140_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.&lt;&gt;c__DisplayClass5_0.&lt;Post&gt;b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run() in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 166
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 208
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG&amp; lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 157
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 107
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 134
   at UABEAvalonia.Program.Main(String[] args) in C:\Users\nesquack\Documents\GitRepos\uabequickfixes\UABEA\UABEAvalonia\Program.cs:line 47
</Data>
  </EventData>
</Event>

**Comment by nesrak1** [comment]
Can you try to reproduce this on the [latest build](https://nightly.link/nesrak1/UABEA/workflows/dotnet-desktop/master/uabea-windows.zip)?

**Comment by karohan** [comment]
.net runtime ; 

"Günlük Adı:    Application
Kaynak:        .NET Runtime
Tarih:         14/01/2022 8:02:57 PM
Olay Kimliği:  1026
Görev Kategorisi:Yok
Düzey:         Hata
Anahtar sözcükler:Klasik
Kullanıcı:     Yok
Bilgisayar:    DESKTOP-CNN3ANN
Açıklama:
Application: UABEAvalonia.exe
CoreCLR Version: 5.0.1321.56516
.NET Version: 5.0.13
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at System.IO.BinaryReader.ReadUInt32()
   at AssetsTools.NET.AssetsFileReader.ReadUInt32()
   at AssetsTools.NET.Type_0D.Read(Boolean hasTypeTree, AssetsFileReader reader, UInt32 version)
   at AssetsTools.NET.TypeTree.Read(AssetsFileReader reader, UInt32 version)
   at AssetsTools.NET.AssetsFile..ctor(AssetsFileReader reader)
   at AssetsTools.NET.Extra.AssetsFileInstance..ctor(Stream stream, String filePath, String root)
   at AssetsTools.NET.Extra.AssetsManager.LoadAssetsFile(Stream stream, String path, Boolean loadDeps, String root, BundleFileInstance bunInst)
   at AssetsTools.NET.Extra.AssetsManager.LoadAssetsFile(FileStream stream, Boolean loadDeps, String root)
   at AssetsTools.NET.Extra.AssetsManager.LoadAssetsFile(String path, Boolean loadDeps, String root)
   at UABEAvalonia.MainWindow.MenuOpen_Click(Object sender, RoutedEventArgs e) in D:\a\UABEA\UABEA\UABEAvalonia\MainWindow.axaml.cs:line 138
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run() in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 166
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 251
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 198
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 126
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 175
   at UABEAvalonia.Program.Main(String[] args) in D:\a\UABEA\UABEA\UABEAvalonia\Program.cs:line 47

Olay Xml'si:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-01-14T17:02:57.5119481Z" />
    <EventRecordID>93378</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-CNN3ANN</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: UABEAvalonia.exe
CoreCLR Version: 5.0.1321.56516
.NET Version: 5.0.13
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at System.IO.BinaryReader.ReadUInt32()
   at AssetsTools.NET.AssetsFileReader.ReadUInt32()
   at AssetsTools.NET.Type_0D.Read(Boolean hasTypeTree, AssetsFileReader reader, UInt32 version)
   at AssetsTools.NET.TypeTree.Read(AssetsFileReader reader, UInt32 version)
   at AssetsTools.NET.AssetsFile..ctor(AssetsFileReader reader)
   at AssetsTools.NET.Extra.AssetsFileInstance..ctor(Stream stream, String filePath, String root)
   at AssetsTools.NET.Extra.AssetsManager.LoadAssetsFile(Stream stream, String path, Boolean loadDeps, String root, BundleFileInstance bunInst)
   at AssetsTools.NET.Extra.AssetsManager.LoadAssetsFile(FileStream stream, Boolean loadDeps, String root)
   at AssetsTools.NET.Extra.AssetsManager.LoadAssetsFile(String path, Boolean loadDeps, String root)
   at UABEAvalonia.MainWindow.MenuOpen_Click(Object sender, RoutedEventArgs e) in D:\a\UABEA\UABEA\UABEAvalonia\MainWindow.axaml.cs:line 138
   at System.Threading.Tasks.Task.&lt;&gt;c.&lt;ThrowAsync&gt;b__140_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.&lt;&gt;c__DisplayClass5_0.&lt;Post&gt;b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run() in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 166
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 251
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG&amp; lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 198
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 126
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 175
   at UABEAvalonia.Program.Main(String[] args) in D:\a\UABEA\UABEA\UABEAvalonia\Program.cs:line 47
</Data>
  </EventData>
</Event>"


applycation Error; 
"Günlük Adı:    Application
Kaynak:        Application Error
Tarih:         14/01/2022 8:02:57 PM
Olay Kimliği:  1000
Görev Kategorisi:(100)
Düzey:         Hata
Anahtar sözcükler:Klasik
Kullanıcı:     Yok
Bilgisayar:    DESKTOP-CNN3ANN
Açıklama:
Hatalı uygulama adı: UABEAvalonia.exe, sürüm: 1.0.0.0, zaman damgası: 0x619336bf
Hatalı modül adı: KERNELBASE.dll, sürüm: 10.0.19041.1387, zaman damgası: 0x0b9a844a
Özel durum kodu: 0xe0434352
Hata uzaklığı 0x0000000000034f69
Hatalı işlem kimliği: 0x2460
Uygulama başlangıç zamanı: 0x01d809687b9cf93c
Hatalı uygulama yolu: D:\Tools\ASSETS EDİT\uabea-windows\UABEAvalonia.exe
Hatalı modül yolu: C:\Windows\System32\KERNELBASE.dll
Rapor kimliği: fb29d762-13ef-4f9e-96d2-be8d355225ef
Hatalı paket tam adı: 
Hatalı paketle ilgili uygulama kimliği: 
Olay Xml'si:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-01-14T17:02:57.9805694Z" />
    <EventRecordID>93379</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-CNN3ANN</Computer>
    <Security />
  </System>
  <EventData>
    <Data>UABEAvalonia.exe</Data>
    <Data>1.0.0.0</Data>
    <Data>619336bf</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.19041.1387</Data>
    <Data>0b9a844a</Data>
    <Data>e0434352</Data>
    <Data>0000000000034f69</Data>
    <Data>2460</Data>
    <Data>01d809687b9cf93c</Data>
    <Data>D:\Tools\ASSETS EDİT\uabea-windows\UABEAvalonia.exe</Data>
    <Data>C:\Windows\System32\KERNELBASE.dll</Data>
    <Data>fb29d762-13ef-4f9e-96d2-be8d355225ef</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>"


windows error reporting;
"Günlük Adı:    Application
Kaynak:        Windows Error Reporting
Tarih:         14/01/2022 8:06:23 PM
Olay Kimliği:  1001
Görev Kategorisi:Yok
Düzey:         Bilgi
Anahtar sözcükler:Klasik
Kullanıcı:     Yok
Bilgisayar:    DESKTOP-CNN3ANN
Açıklama:
Hata demeti 1434535340136134993, tür 5
Olay Adı: CLR20r3
Yanıt: Kullanılamıyor
Kabin Kimliği: 0

Sorun imzası:
P1: JVGYGLNZZVLAI4KF0WDD3T5BGYTDJLNB
P2: 1.0.0.0
P3: 619336bf
P4: System.Private.CoreLib
P5: 5.0.1321.56516
P6: b0a82283
P7: 54c4
P8: 3b
P9: System.IO.EndOfStreamException
P10: 

İliştirilmiş dosyalar:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5580.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5F74.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5FB3.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5FC1.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6010.tmp.txt

Bu dosyalar burada bulunabilir:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_JVGYGLNZZVLAI4KF_f36e77e1ccea91f0c655a5421052abea3ed534_53bcb0aa_acd10b8a-a91d-4e2c-97b0-0da49a6079f4

Çözümleme simgesi: 
Çözüm için yeniden denetleme: 0
Rapor Kimliği: 70742f5e-ecaf-468e-9b3c-779ebe623426
Rapor Durumu: 268435456
Karma demeti: 6aeae47279d6a10df3e87e4a968ef951
Kabin Guid'i: 0
Olay Xml'si:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows Error Reporting" />
    <EventID Qualifiers="0">1001</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-01-14T17:06:23.2779455Z" />
    <EventRecordID>93396</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-CNN3ANN</Computer>
    <Security />
  </System>
  <EventData>
    <Data>1434535340136134993</Data>
    <Data>5</Data>
    <Data>CLR20r3</Data>
    <Data>Kullanılamıyor</Data>
    <Data>0</Data>
    <Data>JVGYGLNZZVLAI4KF0WDD3T5BGYTDJLNB</Data>
    <Data>1.0.0.0</Data>
    <Data>619336bf</Data>
    <Data>System.Private.CoreLib</Data>
    <Data>5.0.1321.56516</Data>
    <Data>b0a82283</Data>
    <Data>54c4</Data>
    <Data>3b</Data>
    <Data>System.IO.EndOfStreamException</Data>
    <Data>
    </Data>
    <Data>
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5580.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5F74.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5FB3.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5FC1.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6010.tmp.txt</Data>
    <Data>\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_JVGYGLNZZVLAI4KF_f36e77e1ccea91f0c655a5421052abea3ed534_53bcb0aa_acd10b8a-a91d-4e2c-97b0-0da49a6079f4</Data>
    <Data>
    </Data>
    <Data>0</Data>
    <Data>70742f5e-ecaf-468e-9b3c-779ebe623426</Data>
    <Data>268435456</Data>
    <Data>6aeae47279d6a10df3e87e4a968ef951</Data>
    <Data>0</Data>
  </EventData>
</Event>"

**Comment by karohan** [comment]
[Denglu.zip](https://github.com/nesrak1/UABEA/files/7872054/Denglu.zip)
Why do you think the problem is caused? What precaution should I take?

**Comment by nesrak1** [comment]
Old style UnityWeb archives are not supported. You can open this file in UABE though.

**Comment by karohan** [comment]
Thank You. Is it possible to get support in the future?

**Comment by nesrak1** [comment]
Support is being added in a PR for AssetsTools.NET https://github.com/nesrak1/AssetsTools.NET/pull/66
