### ISSUE TITLE
crash after a re-modifying a file previously edited using UABEA

### ISSUE THREAD

**Issue by xtremegat** [nesrak1/UABEA#147]
Latest Version of UABEA

Game: Shin Megami Tensei III Nocturne HD Remaster

when modifying a file, like changing a texture and saving it. the game will load fine with the modifications working as intended but if you try to modify the same file again using UABEA. like change another texture that is inside the file. after clicking save in UABEA it will crash and if you try to load the game it will be in a infinite loading screen

log:

Application: UABEAvalonia.exe
CoreCLR Version: 5.0.1321.56516
.NET Version: 5.0.13
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.IOException: The process cannot access the file 'C:\Program Files (x86)\Steam\steamapps\common\smt3hd\smt3hd_Data\StreamingAssets\PC\f011' because it is being used by another process.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.OpenWrite(String path)
   at UABEAvalonia.MainWindow.SaveBundle(BundleFileInstance bundleInst, String path) in D:\a\UABEA\UABEA\UABEAvalonia\MainWindow.axaml.cs:line 653
   at UABEAvalonia.MainWindow.AskForLocationAndSave() in D:\a\UABEA\UABEA\UABEAvalonia\MainWindow.axaml.cs:line 431
   at UABEAvalonia.MainWindow.MenuSave_Click(Object sender, RoutedEventArgs e) in D:\a\UABEA\UABEA\UABEAvalonia\MainWindow.axaml.cs:line 197
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 271
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 198
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 126
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 175
   at UABEAvalonia.Program.Main(String[] args) in D:\a\UABEA\UABEA\UABEAvalonia\Program.cs:line 47

**Comment by nesrak1** [comment]
> Exception Info: System.IO.IOException: The process cannot access the file 'C:\Program Files (x86)\Steam\steamapps\common\smt3hd\smt3hd_Data\StreamingAssets\PC\f011' because it is being used by another process.

Are you overwriting the original file or modifying the file while the game is open?

**Comment by xtremegat** [comment]
I'm modifying the file that i edited using uabea again, and no i am not doing this with the game opened

**Comment by nesrak1** [comment]
I can't reproduce on the latest build. Here's what I did:

1. Open bundle "test.unity3d"
2. Click info
3. Make a modification, save, and close
4. Save the bundle as a new file "test.new.unity3d"
5. Click info again
6. Make another modification, save, and close
7. Save the bundle again as "test.new.unity3d"
8. UABEA does not crash

**Comment by xtremegat** [comment]
I did as you told, and it worked, but if i close UABEA after doing the first modification, and then open it again do the second one it will crash

**Comment by nesrak1** [comment]
Still can't reproduce. Are you sure you aren't replacing the file you opened with the new bundle?
If it helps, the [latest build](https://nightly.link/nesrak1/UABEA/workflows/dotnet-desktop/master/uabea-windows.zip) will prevent you from doing this now.

**Comment by xtremegat** [comment]
this build fixed my issue, thank you
