### ISSUE TITLE
Crash: After importing a dump to a newly added file

### ISSUE THREAD

**Issue by BestPotato** [nesrak1/UABEA#148]
It seems that when you attempt to do anything after importing a dump to a new file causes a crash.

Repro Steps:
1. Launch UABEAvalonia.exe (uabea_rel3_win_x64)
2. Open a .bundle file
3. Select Info
4. Select File > Add
5. Fill information and select Ok
6. Select that file and then import a dump
7. After importing the dump, select View Data (also occurs when attempting to save) and observe that the application crashes

```
Application: UABEAvalonia.exe
CoreCLR Version: 5.0.321.7212
.NET Version: 5.0.3
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at AssetsTools.NET.Extra.MonoDeserializer.ReadTypes(TypeDefinition type) in C:\Users\nesquack\Documents\GitReposLocal\AssetsTools.NET\AssetTools.NET\Extra\MonoDeserializer\MonoDeserializer.cs:line 130
   at AssetsTools.NET.Extra.MonoDeserializer.RecursiveTypeLoad(TypeDefinition type, List`1 attf) in C:\Users\nesquack\Documents\GitReposLocal\AssetsTools.NET\AssetTools.NET\Extra\MonoDeserializer\MonoDeserializer.cs:line 107
   at AssetsTools.NET.Extra.MonoDeserializer.RecursiveTypeLoad(TypeDefinition type, List`1 attf) in C:\Users\nesquack\Documents\GitReposLocal\AssetsTools.NET\AssetTools.NET\Extra\MonoDeserializer\MonoDeserializer.cs:line 104
   at AssetsTools.NET.Extra.MonoDeserializer.RecursiveTypeLoad(ModuleDefinition module, String typeName, List`1 attf) in C:\Users\nesquack\Documents\GitReposLocal\AssetsTools.NET\AssetTools.NET\Extra\MonoDeserializer\MonoDeserializer.cs:line 93
   at AssetsTools.NET.Extra.MonoDeserializer.Read(String typeName, AssemblyDefinition assembly, UInt32 format) in C:\Users\nesquack\Documents\GitReposLocal\AssetsTools.NET\AssetTools.NET\Extra\MonoDeserializer\MonoDeserializer.cs:line 25
   at UABEAvalonia.AssetWorkspace.GetConcatMonoBaseField(AssetContainer cont, String managedPath) in C:\Users\nesquack\Documents\GitRepos\uabequickfixes\UABEA\UABEAvalonia\AssetWorkspace.cs:line 254
   at UABEAvalonia.AssetWorkspace.GetBaseField(AssetContainer cont) in C:\Users\nesquack\Documents\GitRepos\uabequickfixes\UABEA\UABEAvalonia\AssetWorkspace.cs:line 197
   at UABEAvalonia.DataWindow..ctor(AssetWorkspace workspace, AssetContainer cont) in C:\Users\nesquack\Documents\GitRepos\uabequickfixes\UABEA\UABEAvalonia\DataWindow.axaml.cs:line 34
   at UABEAvalonia.InfoWindow.BtnViewData_Click(Object sender, RoutedEventArgs e) in C:\Users\nesquack\Documents\GitRepos\uabequickfixes\UABEA\UABEAvalonia\InfoWindow.axaml.cs:line 241
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 157
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 107
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 134
   at UABEAvalonia.Program.Main(String[] args) in C:\Users\nesquack\Documents\GitRepos\uabequickfixes\UABEA\UABEAvalonia\Program.cs:line 47
```

Please let me know if you need more information.
Also, thank you for the tool. It's been very nice to use!

**Comment by nesrak1** [comment]
> Fill information and select Ok
> Select that file and then import a dump

Can you be more specific what information you filled in and where the dump came from? Also, is the game il2cpp? This issue seems to be specific to MonoBehaviours.

**Comment by BestPotato** [comment]
Here is what I filled in:

> Path ID: 2 
> Type Name/ID: MonoBehaviour
> Mono Class ID: 114
> Fill asset with 00s - Checked
I have also seen the crash when using a path ID of another file.

I exported the dump from another MonoBehaviour file and used that for the new file.

And you are correct! it is an il2cpp title.

**Comment by nesrak1** [comment]
The error you posted suggests that it can't find the List type in the dlls which would only happen if you either didn't copy all of the dlls to the Managed folder or whatever you used to dump dlls didn't include the List type for whatever reason.

Also, I might add that Mono Class ID is not what you think it is. Each MonoBehaviour gets a unique id, although I'm just now realizing there's no way to find out if there's an existing mono id. I think any random number should work for now though.

**Comment by BestPotato** [comment]
Ah, that makes a lot of sense. That was the one bundle where I did not have the managed folder. The issue was resolved once I opened another bundle with the managed folder.

I am running to other crashes but it's more unhandled exceptions due to configurations I'm sure. By any chance do you have a guide or know of one that explains how to properly add content?

Also, appreciate all the help and thanks again for tool!

**Comment by nesrak1** [comment]
Adding assets by File->Add and importing dumps _is_ possible (and the only way to add new assets right now) although it's not very easy, especially with multiple assets. There have been requests for importing bundles built in the editor as a feature but it may take a while for that to happen.

**Comment by BestPotato** [comment]
Good to know.
Funny thing. I downloaded the nightly build and the crashes seem to be resolved. Feel free to close out this issue.

Thanks again!
