### ISSUE TITLE
UABEAvalonia has stopped working

### ISSUE THREAD

**Issue by luatsenpai** [nesrak1/UABEA#15]
Hello, I tried your tool, but when i open file the tool has stopped
How to fix this?
Sorry my bad english
![error](https://user-images.githubusercontent.com/44133093/115946366-e7037c80-a4ea-11eb-8f61-c1fc092db791.png)

**Comment by nesrak1** [comment]
After it crashes, open event viewer and look in Windows Logs -> Application. There should be a .NET Runtime error. Paste the stack trace from there so I can see what's going wrong.

Like this:
![image](https://user-images.githubusercontent.com/12544505/116024164-3a70ea00-a613-11eb-80f2-be574ed79222.png)

Also, if you have a file you can send that will help too.

**Comment by luatsenpai** [comment]
> After it crashes, open event viewer and look in Windows Logs -> Application. There should be a .NET Runtime error. Paste the stack trace from there so I can see what's going wrong.
> 
> Like this:
> ![image](https://user-images.githubusercontent.com/12544505/116024164-3a70ea00-a613-11eb-80f2-be574ed79222.png)
> 
> Also, if you have a file you can send that will help too.

Application: UABEAvalonia.exe
CoreCLR Version: 5.0.521.16609
.NET Version: 5.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException: Value does not fall within the expected range.
   at Avalonia.Win32.Interop.UnmanagedMethods.IShellItem.GetDisplayName(UInt32 sigdnName, IntPtr& ppszName)
   at Avalonia.Win32.SystemDialogImpl.GetAbsoluteFilePath(IShellItem shellItem) in /_/src/Windows/Avalonia.Win32/SystemDialogImpl.cs:line 153
   at Avalonia.Win32.SystemDialogImpl.<>c__DisplayClass1_0.<ShowFileDialogAsync>b__0() in /_/src/Windows/Avalonia.Win32/SystemDialogImpl.cs:line 90
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at UABEAvalonia.MainWindow.MenuOpen_Click(Object sender, RoutedEventArgs e) in C:\Users\nesquack\source\repos\UABEAvalonia\UABEAvalonia\MainWindow.axaml.cs:line 89
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run() in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 166
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 208
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 157
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 107
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 134
   at UABEAvalonia.Program.Main(String[] args) in C:\Users\nesquack\source\repos\UABEAvalonia\UABEAvalonia\Program.cs:line 13

**Comment by nesrak1** [comment]
Looks like this is an Avalonia bug specifically on Windows 7.

Other people have reported that here:

* https://github.com/AvaloniaUI/Avalonia/issues/3272
* https://stackoverflow.com/questions/57257928/avaloniaui-argumentexception-being-thrown-when-openfiledialog-is-used-in-windo

So there's not much I can do until Avalonia pushes a fix.

**Comment by nesrak1** [comment]
I played around a bit with trying to open files in a windows 7 vm and found out that it seems to crash when opening the file from Libraries/My Documents. When opened from UserFolder/Documents opened it fine.

Bad:
![VirtualBoxVM_3iMQ1clipb](https://user-images.githubusercontent.com/12544505/116165462-8ed2a300-a6c1-11eb-9582-7096070c50c3.png)

Good:
![VirtualBoxVM_4cJNKS2XBS](https://user-images.githubusercontent.com/12544505/116165472-909c6680-a6c1-11eb-935f-6cf2706c01fd.png)

**Comment by luatsenpai** [comment]
I tried it and it works, thank :D
