### ISSUE TITLE
UABEA Crash

### ISSUE THREAD

**Issue by louisome** [nesrak1/UABEA#158]
when I open a resource file, and add dump dll to the "Managed" floder,  click the "view data", uabea crash...

here is the event logs.

Application: UABEAvalonia.exe
CoreCLR Version: 5.0.621.22011
.NET Version: 5.0.6
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at AssetsTools.NET.Extra.MonoDeserializer.ReadTypes(TypeDefinition type)
   at AssetsTools.NET.Extra.MonoDeserializer.RecursiveTypeLoad(TypeDefinition type, List`1 attf)
   at AssetsTools.NET.Extra.MonoDeserializer.RecursiveTypeLoad(TypeDefinition type, List`1 attf)
   at AssetsTools.NET.Extra.MonoDeserializer.RecursiveTypeLoad(ModuleDefinition module, String typeName, List`1 attf)
   at AssetsTools.NET.Extra.MonoDeserializer.Read(String typeName, AssemblyDefinition assembly, UInt32 format)
   at UABEAvalonia.AssetWorkspace.GetConcatMonoBaseField(AssetContainer cont, String managedPath) in D:\a\UABEA\UABEA\UABEAvalonia\AssetWorkspace.cs:line 254
   at UABEAvalonia.AssetWorkspace.GetBaseField(AssetContainer cont) in D:\a\UABEA\UABEA\UABEAvalonia\AssetWorkspace.cs:line 197
   at UABEAvalonia.InfoWindow.SingleExportDump(List`1 selection) in D:\a\UABEA\UABEA\UABEAvalonia\InfoWindow.axaml.cs:line 562
   at UABEAvalonia.InfoWindow.BtnExportDump_Click(Object sender, RoutedEventArgs e) in D:\a\UABEA\UABEA\UABEAvalonia\InfoWindow.axaml.cs:line 269
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 271
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 198
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 126
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 175
   at UABEAvalonia.Program.Main(String[] args) in D:\a\UABEA\UABEA\UABEAvalonia\Program.cs:line 47

here is the dummydll (arm-v8).

[DummyDll.zip](https://github.com/nesrak1/UABEA/files/8121724/DummyDll.zip)

here is the resource flie. You can click the "Localization" to "view data".
[98e45fe3aaf0b7a41bed85a7fc5ce7ac.zip](https://github.com/nesrak1/UABEA/files/8121747/98e45fe3aaf0b7a41bed85a7fc5ce7ac.zip)

**Comment by nesrak1** [comment]
The MonoDeserializer doesn't support generic base types at the moment. I'll put it on the list of things to do.
