### ISSUE TITLE
Texture 2D Load causes crash

### ISSUE THREAD

**Issue by BiscuitGames** [nesrak1/UABEA#168]
Not overly knowledgeable, mainly just a photoshop idiot. Every time I try and load a texture replacement, I get this.

```
Application: UABEAvalonia.exe
CoreCLR Version: 5.0.1522.11506
.NET Version: 5.0.15
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at TexturePlugin.EditDialog.BtnSave_Click(Object sender, RoutedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 278
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 205
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at UABEAvalonia.Program.Main(String[] args) in D:\a\UABEA\UABEA\UABEAvalonia\Program.cs:line 47
```

**Comment by nesrak1** [comment]
I'm not sure what could be causing this. Can I get a screenshot of the edit texture window, the version of the game, and if it's free, the name of the game so I can debug it?

**Comment by BiscuitGames** [comment]
![troubleshooting](https://user-images.githubusercontent.com/32503765/160548056-a83c591b-dfe9-4089-ae5e-ba9bdc2aabf9.PNG)

Unfortunately the game isn't free. It's UNO on Steam, Build ID 7701702.

**Comment by nesrak1** [comment]
Sorry I meant the engine version of the game (you can find by right click->properties menu, not the build version. In any case, I know the unity version of it already and it's probably because it's so old.  For now, you should be able to use the old uabe without issues.

**Comment by BiscuitGames** [comment]
![IT WORKS MWAHAHAHAHAHAHAAAAAA](https://user-images.githubusercontent.com/32503765/160552709-7194b2ff-7d23-4b4f-9b03-08b7fb4975cb.png)

You're a legend, the original UABE worked. Have an amazing day!!
