### ISSUE TITLE
Error when save

### ISSUE THREAD

**Issue by katashi123** [nesrak1/UABEA#208]
There was a problem while writing the file:
System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.Strategies.BufferedFileStreamStrategy.Seek(Int64 offset, SeekOrigin origin)
   at System.IO.FileStream.set_Position(Int64 value)
   at AssetsTools.NET.AssetsFileReader.set_Position(Int64 value) in C:\Users\karse\Documents\GitReposLocal\AssetsTools.NET\AssetTools.NET\Standard\IO\AssetsFileReader.cs:line 152
   at AssetsTools.NET.AssetsFile.Write(AssetsFileWriter writer, Int64 filePos, List`1 replacers, ClassDatabaseFile typeMeta) in C:\Users\karse\Documents\GitReposLocal\AssetsTools.NET\AssetTools.NET\Standard\AssetsFileFormat\AssetsFile.cs:line 198
   at UABEAvalonia.InfoWindow.SaveFile(Boolean saveAs) in C:\Users\karse\Documents\GitReposLocal\UABEA\UABEAvalonia\InfoWindow.axaml.cs:line 534

**Comment by nesrak1** [comment]
Can you tell me what you were doing when this happened?

**Comment by katashi123** [comment]
> 



> Can you tell me what you were doing when this happened?

when i edit the file unity 2021.3.6f1 with uabea v5 then press save, tool give the tool gives the above error

**Comment by nesrak1** [comment]
I'm going to need more steps if you want me to reproduce this. List all the steps you took to get her including what kind of file you opened, what changes you made, and when you clicked save.

**Comment by katashi123** [comment]
Sorry for the slow reply,
i am editing the file of the game Bendy and the Dark Revival
When i dump MonoBehaviour and import then press save, tool crash
but when i use uabe v4 it works properly

**Comment by nesrak1** [comment]
Maybe could you do a screen recording of it happening? I opened a sharedassets file and did export dump on a MonoBehaviour, imported it again, pressed file save and nothing went wrong. I even did it multiple times to make sure.

**Comment by katashi123** [comment]
i tried again, but somehow it works again, i don't know why too, thanks a lot

**Comment by nesrak1** [comment]
Weird. Let me know if it happens again.
