### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by lt1023** [nesrak1/UABEA#242]
System.NullReferenceException: Object reference not set to an instance of an object.
   at UABEAvalonia.AssetImportExport.RecurseTextDump(AssetTypeValueField field, Int32 depth) in D:\a\UABEA\UABEA\UABEAvalonia\AssetImportExport.cs:line 42
   at UABEAvalonia.AssetImportExport.DumpTextAsset(StreamWriter sw, AssetTypeValueField baseField) in D:\a\UABEA\UABEA\UABEAvalonia\AssetImportExport.cs:line 37
   at UABEAvalonia.InfoWindow.SingleExportDump(List`1 selection) in D:\a\UABEA\UABEA\UABEAvalonia\InfoWindow.axaml.cs:line 767
   at UABEAvalonia.InfoWindow.BtnExportDump_Click(Object sender, RoutedEventArgs e) in D:\a\UABEA\UABEA\UABEAvalonia\InfoWindow.axaml.cs:line 332
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 38
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 298
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 215
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 122
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 214
   at UABEAvalonia.Program.Main(String[] args) in D:\a\UABEA\UABEA\UABEAvalonia\Program.cs:line 53

**Comment by nesrak1** [comment]
It's probably a MonoBehaviour and clicking view data should correctly handle the error and say that it can't be deserialized. If it is, it's probably the issue with the version of cpp2il used at the moment. You can turn it off in the options menu on the main window and put dummy dlls in the managed folder as a temporary workaround.

**Comment by lt1023** [comment]
yes，crashed when i   put dlls folder in res。now，i just mod dat file，but i dont know how to modify pathId，can you help me？thank u ！

**Comment by lt1023** [comment]
its my dlls and .unity3d~~

https://onedrive.live.com/?authkey=%21ADuahlRKrWL2O7Q&cid=A398EDA0FC81F0E9&id=A398EDA0FC81F0E9%21109&parId=root&o=OneUp
