### ISSUE TITLE
Unable to save, throw System.IO.IOException: Stream was too long.

### ISSUE THREAD

**Issue by ob2code** [nesrak1/UABEA#244]
Hello. When I try to save after importing or editing data with data.unity3d file (decompressed file nearly 6GB), the application throw this message below and the file doesn't update anything.

![screenshot_1683390239](https://user-images.githubusercontent.com/813037/236635716-8a2d3177-77d5-4504-86e8-707dbe05b0a1.png)

File link:
https://1drv.ms/u/s!Ah9obHc_yBz_gQsln9Ac3tQkbEQD?e=M3xrr5

`There was a problem while writing the file:
System.IO.IOException: Stream was too long.
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at AssetsTools.NET.Extra.Net35Polyfill.CopyToCompat(Stream input, Stream output, Int64 bytes, Int32 bufferSize)
   at AssetsTools.NET.AssetsFile.Write(AssetsFileWriter writer, Int64 filePos, List`1 replacers, ClassDatabaseFile typeMeta)
   at UABEAvalonia.InfoWindow.SaveFile(Boolean saveAs) in D:\a\UABEA\UABEA\UABEAvalonia\InfoWindow.axaml.cs:line 509`

**Comment by nesrak1** [comment]
This is a limitation of C#'s byte arrays and memory streams having a 2GB limit. You can avoid this by clicking "export all", making your changes there, then clicking "import all" and selecting the folder. This avoids ever having to keep the entire file in memory at once.

**Comment by ob2code** [comment]
It works. Thank you very much!
