### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by willil58** [nesrak1/UABEA#245]
System.Runtime.InteropServices.COMException (0x80004005): The parameter is incorrect.
 ---> System.Runtime.InteropServices.COMException (0x80070057): GetResults failed
   at Avalonia.Win32.Win32Com.Impl.__MicroComIFileOpenDialogProxy.get_Results() in /_/src/Windows/Avalonia.Win32/Win32Com/Win32.Generated.cs:line 1866
   at Avalonia.Win32.Win32StorageProvider.<>c__DisplayClass13_0.<ShowFilePicker>b__0() in /_/src/Windows/Avalonia.Win32/Win32StorageProvider.cs:line 160
   at Avalonia.Win32.Win32StorageProvider.<>c__DisplayClass13_0.<ShowFilePicker>b__0() in /_/src/Windows/Avalonia.Win32/Win32StorageProvider.cs:line 186
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Avalonia.Win32.Win32StorageProvider.OpenFilePickerAsync(FilePickerOpenOptions options) in /_/src/Windows/Avalonia.Win32/Win32StorageProvider.cs:line 47
   at UABEAvalonia.MainWindow.MenuOpen_Click(Object sender, RoutedEventArgs e) in D:\a\UABEA\UABEA\UABEAvalonia\MainWindow.axaml.cs:line 194
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.JobRunner.JobWithArg.Avalonia.Threading.JobRunner.IJob.Run() in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 241
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 38
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 298
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 215
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 122
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 214
   at UABEAvalonia.Program.Main(String[] args) in D:\a\UABEA\UABEA\UABEAvalonia\Program.cs:line 53

**Comment by nesrak1** [comment]
So this happened when you opened a file picker? Does this always happen or just once? I don't think this is anything I can fix, it might be an Avalonia issue.

**Comment by willil58** [comment]
It always happens. I have a .bundle file for a game I’m working on. I’ve tried selecting the file then selecting open with uabea and opening uabea first then going to file > open and selecting the file. The first method nothing happens. The second method causes it to crash.

**Comment by nesrak1** [comment]
Can you try dragging the file onto the window?

**Comment by willil58** [comment]
I'm on Windows 7 (old I know but I use a mac and this was what I was able to get a hold of). When I drag it I'm able to go into the file but as soon as I try to replace the texture file it crashes again.

**Comment by nesrak1** [comment]
I guess this is only after you select the file that the crash happens? I asked about OS because previously, a windows 7 user had crashes when opening something through the normal documents/downloads/etc. folders, but worked fine when they manually went to `c:\users\user bame\documents\the file`. I was trying to find the issue but I can't find it right now.

**Comment by willil58** [comment]
Just noticed I get a different error when I drag and drop the file. It lets me open the .bundle file and load the new texture I want to use but then won't let me save it. Here's what I see after I hit save: SixLabors.ImageSharp.UnknownImageFormatException: Image cannot be loaded. Available decoders:
 - TIFF : TiffDecoder
 - JPEG : JpegDecoder
 - PNG : PngDecoder
 - TGA : TgaDecoder
 - PBM : PbmDecoder
 - Webp : WebpDecoder
 - GIF : GifDecoder
 - BMP : BmpDecoder

   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration configuration, Stream stream, IImageFormat& format)
   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration configuration, Stream stream)
   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration configuration, String path)
   at SixLabors.ImageSharp.Image.Load[TPixel](String path)
   at TexturePlugin.EditDialog.BtnSave_Click(Object sender, RoutedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 38
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 298
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 215
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 122
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 214
   at UABEAvalonia.Program.Main(String[] args) in D:\a\UABEA\UABEA\UABEAvalonia\Program.cs:line 53

**Comment by nesrak1** [comment]
This could be a few things. Are you still opening through `Libraries / Documents` or through `C:\Users\User\Documents`? I can't tell if ImageSharp was passed something like an empty string or if the image you opened is just invalid.

**Comment by willil58** [comment]
It was the image for some reason. I got it to work now and I was still doing libraries/docs!

**Comment by nesrak1** [comment]
Okay, cool. I wish I could help with the open file dialog issues, but those are Avalonia specific and not something I can directly fix in UABEA. I would make an issue over there, except I don't have any Windows 7 computer to use to test and get more info on.
