### ISSUE TITLE
I cannot save any files

### ISSUE THREAD

**Issue by theman12222** [nesrak1/UABEA#265]
Whenever i try saving a file, it saves to around 300 kilobytes then the Message box says 
There was a problem while writing the file:
System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.Strategies.BufferedFileStreamStrategy.Seek(Int64 offset, SeekOrigin origin)
   at System.IO.FileStream.set_Position(Int64 value)
   at AssetsTools.NET.AssetsFileReader.set_Position(Int64 value)
   at AssetsTools.NET.AssetsFile.Write(AssetsFileWriter writer, Int64 filePos, List`1 replacers, ClassDatabaseFile typeMeta)
   at UABEAvalonia.InfoWindow.SaveFile(Boolean saveAs) in D:\a\UABEA\UABEA\UABEAvalonia\InfoWindow.axaml.cs:line 576
If it helps i'm attempting to edit one of the textures for yandere simulator, but it loads the files just fine so i don't see why it shouldn't be able to save them. Please help. sorry the video is low quality

https://github.com/nesrak1/UABEA/assets/112595465/7fa70b38-f010-43cb-86ec-1c324c2d0358

**Comment by nesrak1** [comment]
I can't tell because the recording is so low res, but is this a bundle or assets file you opened? (Looks like assets file but not sure.) Did you close the starting window? I only see a preview of the asset info window open.

**Comment by theman12222** [comment]
I have a higher quality recording. It's an asset file, i didn't close the starting window.

https://github.com/nesrak1/UABEA/assets/112595465/d3b146df-b9c7-444c-a8f2-e0078b9afd71

**Comment by nesrak1** [comment]
You've tried restarting and this still happens? Can you list the steps you did?

**Comment by theman12222** [comment]
Yes, i've restarted and it still does it. I open a sharedassets file, edit one of the textures, then attempt to save it and every time it does that. I tried installing the nightly version before opening this and it still did the same thing

**Comment by nesrak1** [comment]
Are you using save or save as initially?

**Comment by theman12222** [comment]
I tried save initially but then it just said
There was a problem while writing the file:
System.IO.IOException: The process cannot access the file 'C:\Users\Pcadm\Downloads\latest\YandereSimulator_Data\resources.assets' because it is being used by another process.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at UABEAvalonia.InfoWindow.SaveFile(Boolean saveAs) in D:\a\UABEA\UABEA\UABEAvalonia\Forms\InfoWindow.axaml.cs:line 587

**Comment by nesrak1** [comment]
The regular save option will try to delete and replace the file. It sounds like there's another program that has it open still. Sometimes if you delete it yourself it will say `This file can't be deleted because it's still open in XXX`, where XXX is hopefully the name of the program and not "another application".

**Comment by theman12222** [comment]
Oh yeah i'm just dumb, i had AssetStudio open while i was trying to save it lol. Thanks

**Comment by nesrak1** [comment]
I'll still want to fix this so I'm reopening it.

**Comment by theman12222** [comment]
Alright i gotchu

**Comment by nesrak1** [comment]
This issue was fixed already in https://github.com/nesrak1/UABEANext (has an error message), but I probably won't be back porting it to UABEA.

**Comment by Owlz71** [comment]
Damn, I did the same thing — had AssetStudio open at the same time
