### ISSUE TITLE
Huge asset bundle saves failed

### ISSUE THREAD

**Issue by nsYW** [nesrak1/UABEA#274]
**Describe the bug**
When I save a huge modified unity3d file, there will be pop a write exception window. And it represent:
here was a problem while writing the file:
```
**System.IO.IOException: Stream was too long.
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at AssetsTools.NET.Extra.Net35Polyfill.CopyToCompat(Stream input, Stream output, Int64 bytes, Int32 bufferSize)
   at AssetsTools.NET.AssetsFile.Write(AssetsFileWriter writer, Int64 filePos, List`1 replacers, ClassDatabaseFile typeMeta)
   at UABEAvalonia.InfoWindow.SaveFile(Boolean saveAs) in D:\a\UABEA\UABEA\UABEAvalonia\InfoWindow.axaml.cs:line 509**
```

**_PS: this exception only happens in UABEA, UABE can save the file easily._**

**To Reproduce**
1. Click the "File", then click the "Save" or press "Ctrl+s"
2. See error

**Expected behavior**
here was a problem while writing the file:
```
System.IO.IOException: Stream was too long.
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at AssetsTools.NET.Extra.Net35Polyfill.CopyToCompat(Stream input, Stream output, Int64 bytes, Int32 bufferSize)
   at AssetsTools.NET.AssetsFile.Write(AssetsFileWriter writer, Int64 filePos, List`1 replacers, ClassDatabaseFile typeMeta)
   at UABEAvalonia.InfoWindow.SaveFile(Boolean saveAs) in D:\a\UABEA\UABEA\UABEAvalonia\InfoWindow.axaml.cs:line 509
```

**Screenshots**
![图片](https://github.com/nesrak1/UABEA/assets/24467602/3aeee936-b699-4eb4-b0cf-2605451e7e13)

**Additional context**
N/A

**Comment by nesrak1** [comment]
This is less of a "bug" and more of a known limitation. I didn't actually expect anyone to find a bundle with a single file with a size larger than 2GB, very impressive.

What happens when you save is that UABEA saves the file to memory so that if you close the window but click info again, it can be reopened with the changes you made. However, `MemoryStream`s in .NET (the thing holding that memory) can only be 2GB maximum.

> **PS: this exception only happens in UABEA, UABE can save the file easily.**

UABE is most likely using an from assets replacer which only holds the changes you make in memory instead of the entire file. While I could do that for this version of UABEA, it would be a decent amount of rework. The new version of UABEA already does replacers from assets, so when that fully releases, you'll get the fix with it.

**Comment by nsYW** [comment]
Thank you for your reply, I'm trying to replace the font files in Blasphemous I. Very much looking forward to the next version of UABEA!

**Comment by Hexaae** [comment]
Can't wait for next release! Just got the same issue.

**Comment by nesrak1** [comment]
@Hexaae If [UABEANext](https://github.com/nesrak1/UABEANext) has the features you need already, you can try it out. It should be designed to handle more than 2GB file sizes.

**Comment by Hexaae** [comment]
Mmmmh UABEANext still crashed with Blasphemous trying to edit data.unity.3d\resources.assets\LanguageSource (path ID: 25608) after you File/Save from menu:

![image](https://github.com/user-attachments/assets/86aa85da-2b7c-4210-91f0-4838c2fb1642)

**Comment by nesrak1** [comment]
This is a different issue due to how uncompressed bundles are chunked since how many chunks are needed has to be somehow guessed before the chunks are even written.
As for filtering, you can filter by a type by just searching for the type name. If it is a valid type name, it will filter by type (and name).

**Comment by Hexaae** [comment]
Hope it can be fixed too ;)
