### ISSUE TITLE
UABEA Crashes when trying to load BeeByte obfuscated scripts (names?)

### ISSUE THREAD

**Issue by raphaelreal** [nesrak1/UABEA#278]
Whenever I try to get to the ႤႥ႙Ⴃ႙႟ႡႥႢႨႠ.cs file UABEA crashes. It is the only file i need to extract raw but i cant because it crashes. The Script is BeeByte Obfuscated.

**Comment by nesrak1** [comment]
Upload the uabeacrash.log file or I can't do anything

**Comment by raphaelreal** [comment]
System.ArgumentNullException: Value cannot be null. (Parameter 'textBlob')
   at Avalonia.Skia.GlyphRunImpl..ctor(SKTextBlob textBlob, Size size, Point baselineOrigin) in /_/src/Skia/Avalonia.Skia/GlyphRunImpl.cs:line 12
   at Avalonia.Skia.PlatformRenderInterface.CreateGlyphRun(IGlyphTypeface glyphTypeface, Double fontRenderingEmSize, IReadOnlyList`1 glyphInfos, Point baselineOrigin) in /_/src/Skia/Avalonia.Skia/PlatformRenderInterface.cs:line 272
   at Avalonia.Media.GlyphRun.CreateGlyphRunImpl() in /_/src/Avalonia.Base/Media/GlyphRun.cs:line 830
   at Avalonia.Media.TextFormatting.TextLineImpl.CreateLineMetrics() in /_/src/Avalonia.Base/Media/TextFormatting/TextLineImpl.cs:line 1442
   at Avalonia.Media.TextFormatting.TextLineImpl.FinalizeLine() in /_/src/Avalonia.Base/Media/TextFormatting/TextLineImpl.cs:line 1116
   at Avalonia.Media.TextFormatting.TextFormatterImpl.FormatLine(ITextSource textSource, Int32 firstTextSourceIndex, Double paragraphWidth, TextParagraphProperties paragraphProperties, TextLineBreak previousLineBreak) in /_/src/Avalonia.Base/Media/TextFormatting/TextFormatterImpl.cs:line 84
   at Avalonia.Media.TextFormatting.TextLayout.CreateTextLines() in /_/src/Avalonia.Base/Media/TextFormatting/TextLayout.cs:line 478
   at Avalonia.Controls.TextBlock.CreateTextLayout(String text) in /_/src/Avalonia.Controls/TextBlock.cs:line 636
   at Avalonia.Controls.TextBlock.get_TextLayout() in /_/src/Avalonia.Controls/TextBlock.cs:line 175
   at Avalonia.Controls.TextBlock.RenderCore(DrawingContext context) in /_/src/Avalonia.Controls/TextBlock.cs:line 587
   at Avalonia.Rendering.Composition.CompositingRenderer.UpdateCore() in /_/src/Avalonia.Base/Rendering/Composition/CompositingRenderer.cs:line 274
   at Avalonia.Rendering.Composition.CompositingRenderer.Update() in /_/src/Avalonia.Base/Rendering/Composition/CompositingRenderer.cs:line 308
   at Avalonia.Rendering.Composition.Compositor.CommitCore() in /_/src/Avalonia.Base/Rendering/Composition/Compositor.cs:line 108
   at Avalonia.Rendering.Composition.Compositor.Commit() in /_/src/Avalonia.Base/Rendering/Composition/Compositor.cs:line 98
   at Avalonia.Rendering.Composition.CompositingRenderer.Dispose() in /_/src/Avalonia.Base/Rendering/Composition/CompositingRenderer.cs:line 363
   at Avalonia.Controls.TopLevel.HandleClosed() in /_/src/Avalonia.Controls/TopLevel.cs:line 491
   at Avalonia.Controls.WindowBase.HandleClosed() in /_/src/Avalonia.Controls/WindowBase.cs:line 202
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs:line 102
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.WndProc.cs:line 26

**Comment by nesrak1** [comment]
Sorry for not replying earlier. This is an Avalonia issue, so I'll need to make an issue over there when I have the time.
