### ISSUE TITLE
Could you add to DerPopo's UABE ?

### ISSUE THREAD

**Issue by HyperSnip3r** [nesrak1/UABEA#28]
1st let me say that I've no idea how you or DerPopo make these UABE's but thanks for doing so.
Is there a way to add to https://github.com/DerPopo/UABE or are they completely incompatable ? The only problem with DerPopo's is it can't open shared assets files since the April updates while your UABE can.

The issue I ran into with the latest release is while you can add png's through Edit they don't stay added and it bugs after Saving at least for me

**Comment by nesrak1** [comment]
> Is there a way to add to https://github.com/DerPopo/UABE or are they completely incompatable ? The only problem with DerPopo's is it can't open shared assets files since the April updates while your UABE can.

The point of this project is to rewrite the otherwise closed source UABE for newer versions of unity. I can't merge any code because it's not open source and also because it's written in a different language.

> The issue I ran into with the latest release is while you can add png's through Edit they don't stay added and it bugs after Saving at least for me

Any more details about this? Did you save both in the sharedassets file and the bundle or just one? Did the asset show in the Modified column with the * symbol?

I tried just now to edit a texture on the latest Among Us and it seems to be working fine.

**Comment by HyperSniper1982** [comment]
Cool
Hats are my thing to edit for AEW Wrestlers on Twitch. The Hats png in shared assets when downloaded were all blue which was odd, I edited it, saved it. Reopen UABE were Hats is, Plugins, Edit, Load and the hit save. The button darkens and slightly glitches. The star did show up but the shared assets file never came up. On DerPopo UABE's if you saved after i added a png it would create that shared assets file you are talking about but it doesn't on this. On Among Us itself the Hats were the same and didn't show anything I did to them

**Comment by nesrak1** [comment]
I was testing on Among Us mobile so it was a little different. Can you tell me what the texture format shows as in the edit window? Also, you said the asset shows as modified, but when you click file->save nothing happens? It should ask you where you want to save the file.

> The star did show up but the shared assets file never came up

I don't know what you mean by "never came up"

**Comment by HyperSniper1982** [comment]
https://user-images.githubusercontent.com/11294440/117560004-e0940980-b081-11eb-8941-41a0596e5521.mp4

**Comment by nesrak1** [comment]
I didn't realize how slow bcn encoding was. Guess I'll have to swap it out for a native library. The hats texture being the wrong color has been fixed, I converted bgra->rgba for dxt1/5 but not for bc7.
It's fine if the save as box has no filter when you save, you can still call the file whatever you want like `sharedassets0-edited.assets`.

**Comment by HyperSniper1982** [comment]
Can you please tell a noob how to do this " I converted bgra->rgba for dxt1/5 but not for bc7. " I see Texture Plugin was updated, How do I add that to the latest release ?
Please and Thanks

**Comment by nesrak1** [comment]
Since I'll be updating a lot, I'll try to set up automatic builds on all code changes soon.

**Comment by HyperSniper1982** [comment]
Cool, Thanks again

**Comment by nesrak1** [comment]
Automatic builds are set up now here: https://github.com/nesrak1/UABEA/actions
Just click on the latest build and scroll down to the artifacts section and download uabea-windows.

**Comment by HyperSniper1982** [comment]
After I click Save the UABE just closes down
https://user-images.githubusercontent.com/11294440/117587557-74171a00-b116-11eb-9fc8-39856aec22d5.mp4

**Comment by HyperSniper1982** [comment]
After I click Save the UABE just closes down

**Comment by nesrak1** [comment]
Hmm, I tested multiple BC7 textures with import/export and it's working fine on my end. Can you paste the [stack trace](https://github.com/nesrak1/UABEA/issues/15#issuecomment-826471729)?

**Comment by HyperSnip3r** [comment]
Is this what you are looking for ?
Application: UABEAvalonia.exe
CoreCLR Version: 5.0.521.16609
.NET Version: 5.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DllNotFoundException: Unable to load DLL 'textoolwrap' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at TexturePlugin.PInvoke.EncodeByISPC(IntPtr data, IntPtr buf, Int32 mode, Int32 level, UInt32 width, UInt32 height)
   at TexturePlugin.TextureEncoderDecoder.Encode(Byte[] data, Int32 width, Int32 height, TextureFormat format, Int32 quality)
   at TexturePlugin.EditDialog.BtnSave_Click(Object sender, RoutedEventArgs e)
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 152
   at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 79
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/Interactive.cs:line 121
   at Avalonia.Controls.Button.OnClick() in /_/src/Avalonia.Controls/Button.cs:line 269
   at Avalonia.Controls.Button.OnPointerReleased(PointerReleasedEventArgs e) in /_/src/Avalonia.Controls/Button.cs:line 308
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 145
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 148
   at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 79
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/Interactive.cs:line 121
   at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice device, UInt64 timestamp, IInputRoot root, Point p, PointerPointProperties props, KeyModifiers inputModifiers) in /_/src/Avalonia.Input/MouseDevice.cs:line 303
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e) in /_/src/Avalonia.Input/MouseDevice.cs:line 140
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e) in /_/src/Avalonia.Input/InputManager.cs:line 37
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs:line 468
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.WndProc.cs:line 33
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 157
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 107
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 134
   at UABEAvalonia.Program.Main(String[] args) in D:\a\UABEA\UABEA\UABEAvalonia\Program.cs:line 47

**Comment by HyperSnip3r** [comment]
Or this
 - <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name=".NET Runtime" /> 
  <EventID Qualifiers="0">1026</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2021-05-09T22:44:21.4514131Z" /> 
  <EventRecordID>35121</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>Antec-Comp</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>Application: UABEAvalonia.exe CoreCLR Version: 5.0.521.16609 .NET Version: 5.0.5 Description: The process was terminated due to an unhandled exception. Exception Info: System.DllNotFoundException: Unable to load DLL 'textoolwrap' or one of its dependencies: The specified module could not be found. (0x8007007E) at TexturePlugin.PInvoke.EncodeByISPC(IntPtr data, IntPtr buf, Int32 mode, Int32 level, UInt32 width, UInt32 height) at TexturePlugin.TextureEncoderDecoder.Encode(Byte[] data, Int32 width, Int32 height, TextureFormat format, Int32 quality) at TexturePlugin.EditDialog.BtnSave_Click(Object sender, RoutedEventArgs e) at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 152 at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 79 at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/Interactive.cs:line 121 at Avalonia.Controls.Button.OnClick() in /_/src/Avalonia.Controls/Button.cs:line 269 at Avalonia.Controls.Button.OnPointerReleased(PointerReleasedEventArgs e) in /_/src/Avalonia.Controls/Button.cs:line 308 at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 145 at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 148 at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 79 at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/Interactive.cs:line 121 at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice device, UInt64 timestamp, IInputRoot root, Point p, PointerPointProperties props, KeyModifiers inputModifiers) in /_/src/Avalonia.Input/MouseDevice.cs:line 303 at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e) in /_/src/Avalonia.Input/MouseDevice.cs:line 140 at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e) in /_/src/Avalonia.Input/InputManager.cs:line 37 at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs:line 468 at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.WndProc.cs:line 33 at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg) at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 157 at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61 at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 107 at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 134 at UABEAvalonia.Program.Main(String[] args) in D:\a\UABEA\UABEA\UABEAvalonia\Program.cs:line 47</Data> 
  </EventData>
  </Event>

**Comment by nesrak1** [comment]
I've recompiled ispc in release mode. Let me know if it still doesn't work.

**Comment by HyperSnip3r** [comment]
Yeah this 1 https://nightly.link/nesrak1/UABEA/workflows/dotnet-desktop/master/uabea-windows.zip is now working , Cheers
