### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by raysTF** [nesrak1/UABEA#284]
System.NullReferenceException: Object reference not set to an instance of an object.
   at AudioPlugin.ExportAudioClipOption.SelectionValidForPlugin(AssetsManager am, UABEAPluginAction action, List`1 selection, String& name)
   at UABEAvalonia.Plugins.PluginManager.GetPluginsThatSupport(AssetsManager am, List`1 selectedAssets) in D:\a\UABEA\UABEA\UABEAvalonia\Plugins\PluginManager.cs:line 68
   at UABEAvalonia.PluginWindow..ctor(Window win, AssetWorkspace workspace, List`1 selection, PluginManager plugLoader) in D:\a\UABEA\UABEA\UABEAvalonia\Forms\PluginWindow.axaml.cs:line 36
   at UABEAvalonia.InfoWindow.BtnPlugin_Click(Object sender, RoutedEventArgs e) in D:\a\UABEA\UABEA\UABEAvalonia\Forms\InfoWindow.axaml.cs:line 411
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at UABEAvalonia.Program.Main(String[] args) in D:\a\UABEA\UABEA\UABEAvalonia\Program.cs:line 53

**This happens when I press "plugins" after selecting anything.**

**Comment by nesrak1** [comment]
What version is the game? Is this a bundle? This sounds like the tpk didn't load.

**Comment by raysTF** [comment]
I don't know how to tell what the engine version the game is using, but somebody told me it was "2021.3.19f1". It is a bundle file.

**Comment by Danny42** [comment]
Im getting this error as well. Don't know what to do to resolve this

**Comment by nesrak1** [comment]
Probably related to #324.
