### ISSUE TITLE
Can't save the file after editing

### ISSUE THREAD

**Issue by ZizekSlavoj** [nesrak1/UABEA#299]
**Describe the bug**

I opened a resource file and edit it(just edit one number).But when I clicked "save" or "save as".It alerted that "There was a problem while writing the file:
System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.Strategies.BufferedFileStreamStrategy.Seek(Int64 offset, SeekOrigin origin)
   at System.IO.FileStream.set_Position(Int64 value)
   at AssetsTools.NET.AssetsFileReader.set_Position(Int64 value)
   at AssetsTools.NET.AssetsFile.Write(AssetsFileWriter writer, Int64 filePos, List`1 replacers, ClassDatabaseFile typeMeta)
   at UABEAvalonia.InfoWindow.SaveFile(Boolean saveAs) in D:\a\UABEA\UABEA\UABEAvalonia\InfoWindow.axaml.cs:line 576"
![Snipaste_2024-01-01_14-10-02](https://github.com/nesrak1/UABEA/assets/150511030/43ec6baa-9b56-44e6-95df-5961f5f073c4)

**Comment by nesrak1** [comment]
Pretty sure this is #265 . Just make sure nothing else has the file open before you save.
