### ISSUE TITLE
Unhandled exception immediately after opening some compressed bundles

### ISSUE THREAD

**Issue by SacriGrape** [nesrak1/UABEA#31]
Error
```
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'input')
   at System.IO.BinaryReader..ctor(Stream input, Encoding encoding, Boolean leaveOpen)
   at System.IO.BinaryReader..ctor(Stream input)
   at AssetsTools.NET.AssetsFileReader..ctor(Stream stream)
   at UABEAvalonia.AssetBundleUtil.IsBundleDataCompressed(AssetBundleFile bundle) in C:\Users\nesquack\Documents\GitRepos\UABEA\UABEAvalonia\AssetBundleUtil.cs:line 54
   at UABEAvalonia.MainWindow.MenuOpen_Click(Object sender, RoutedEventArgs e) in C:\Users\nesquack\Documents\GitRepos\UABEA\UABEAvalonia\MainWindow.axaml.cs:line 131
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run() in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 166
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 208
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 157
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 107
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 134
   at UABEAvalonia.Program.Main(String[] args) in C:\Users\nesquack\Documents\GitRepos\UABEA\UABEAvalonia\Program.cs:line 47

```
I'm attempting to open one of the bundles from Seven Deadly Sins Grand Cross.
Included is one of the files that has the issue. I have successfully opened *some* of the bundles so this doesn't effect all of them however it does cause issues with quite a few.

https://drive.google.com/file/d/1M4m0ue7-Udp4jFuK9Mw-vM5tpEedBHxe/view?usp=sharing

**Comment by nesrak1** [comment]
This file has a non-standard header so you won't be able to open it normally. You can delete the whole fake header (the first UnityFS to the beginning of the second UnityFS) in a hex editor to fix it.

**Comment by SacriPudding** [comment]
> This file has a non-standard header so you won't be able to open it normally. You can delete the whole fake header (the beginning of the file to the beginning of the second UnityFS) in a hex editor to fix it.

This worked, thank you so much!

I wonder if this is also why AssetStudio just doesn't show some things I would expect it to show.
