### ISSUE TITLE
A problem

### ISSUE THREAD

**Issue by litao1999** [nesrak1/UABEA#315]
Plugin Export texture has crashed. Stacktrace:
System.DllNotFoundException: Unable to load DLL 'textoolwrap' or one of its dependencies. (0x8007007E)
   at TexturePlugin.PInvoke.DecodeByPVRTexLib(IntPtr data, IntPtr buf, Int32 mode, UInt32 width, UInt32 height)
   at TexturePlugin.TextureEncoderDecoder.DecodePVRTexLib(Byte[] data, Int32 width, Int32 height, TextureFormat format)
   at TexturePlugin.TextureEncoderDecoder.Decode(Byte[] data, Int32 width, Int32 height, TextureFormat format)
   at TexturePlugin.TextureImportExport.Export(Byte[] encData, Int32 width, Int32 height, TextureFormat format, UInt32 platform, Byte[] platformBlob)
   at TexturePlugin.TextureImportExport.Export(Byte[] encData, String imagePath, Int32 width, Int32 height, TextureFormat format, UInt32 platform, Byte[] platformBlob)
   at TexturePlugin.ExportTextureOption.SingleExport(Window win, AssetWorkspace workspace, List`1 selection)
   at TexturePlugin.ExportTextureOption.ExecutePlugin(Window win, AssetWorkspace workspace, List`1 selection)
   at UABEAvalonia.PluginWindow.BtnOk_Click(Object sender, RoutedEventArgs e) in D:\a\UABEA\UABEA\UABEAvalonia\Forms\PluginWindow.axaml.cs:line 53

**Comment by nesrak1** [comment]
Duplicate: https://github.com/nesrak1/UABEA/issues/218#issuecomment-1399592063
