### ISSUE TITLE
export dump crashed

### ISSUE THREAD

**Issue by moemoee** [nesrak1/UABEA#322]
when i open .assets file and click a MonoBehaviour file ->  export dump --> uabea crashed 
System.NullReferenceException: Object reference not set to an instance of an object.
   at UABEAvalonia.AssetImportExport.RecurseTextDump(AssetTypeValueField field, Int32 depth) in D:\a\UABEA\UABEA\UABEAvalonia\AssetImportExport.cs:line 42
   at UABEAvalonia.AssetImportExport.DumpTextAsset(StreamWriter sw, AssetTypeValueField baseField) in D:\a\UABEA\UABEA\UABEAvalonia\AssetImportExport.cs:line 37
   at UABEAvalonia.InfoWindow.SingleExportDump(List`1 selection) in D:\a\UABEA\UABEA\UABEAvalonia\InfoWindow.axaml.cs:line 767
   at UABEAvalonia.InfoWindow.BtnExportDump_Click(Object sender, RoutedEventArgs e) in D:\a\UABEA\UABEA\UABEAvalonia\InfoWindow.axaml.cs:line 332
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 38
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 298
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 215
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 122
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 214
   at UABEAvalonia.Program.Main(String[] args) in D:\a\UABEA\UABEA\UABEAvalonia\Program.cs:line 53
https://mega.nz/file/tiYlRRhL#ApMCYgZ04GK10giNbg9DMg6x1gzrXQ0_c55TcKBU32o

**Comment by nesrak1** [comment]
I'm guessing you aren't using nigthly? Exceptions from export dump are caught now.
