### ISSUE TITLE
uabeacrash

### ISSUE THREAD

**Issue by rocho1337** [nesrak1/UABEA#325]
When i click on plugins, uabea crashes with this error. I used nightly version and installed all requirements

Crash report:
System.NullReferenceException: Object reference not set to an instance of an object.
   at AudioPlugin.ExportAudioClipOption.SelectionValidForPlugin(AssetsManager am, UABEAPluginAction action, List`1 selection, String& name)
   at UABEAvalonia.Plugins.PluginManager.GetPluginsThatSupport(AssetsManager am, List`1 selectedAssets) in D:\a\UABEA\UABEA\UABEAvalonia\Plugins\PluginManager.cs:line 68
   at UABEAvalonia.PluginWindow..ctor(Window win, AssetWorkspace workspace, List`1 selection, PluginManager plugLoader) in D:\a\UABEA\UABEA\UABEAvalonia\Forms\PluginWindow.axaml.cs:line 36
   at UABEAvalonia.InfoWindow.BtnPlugin_Click(Object sender, RoutedEventArgs e) in D:\a\UABEA\UABEA\UABEAvalonia\Forms\InfoWindow.axaml.cs:line 408
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at UABEAvalonia.Program.Main(String[] args) in D:\a\UABEA\UABEA\UABEAvalonia\Program.cs:line 53

**Comment by nesrak1** [comment]
You posted the same thing as posted in #324 but 5 hours later so I'm closing this one.
