### ISSUE TITLE
Crashes when Batch importing textures.

### ISSUE THREAD

**Issue by NikolasL015** [nesrak1/UABEA#330]
I'm using the nightly version, but it still crashes every time I try to import multiple textures2d at once (all the texture names are correct).

**LOG:**
Plugin Batch import textures has crashed. Stacktrace:
System.InvalidOperationException: Target width 0 and height 0 must be greater than zero.
   at SixLabors.ImageSharp.Processing.Processors.Transforms.ResizeHelper.ThrowInvalid(String message)
   at SixLabors.ImageSharp.Processing.Processors.Transforms.ResizeHelper.CalculateTargetLocationAndBounds(Size sourceSize, ResizeOptions options)
   at SixLabors.ImageSharp.Processing.Processors.Transforms.ResizeProcessor..ctor(ResizeOptions options, Size sourceSize)
   at SixLabors.ImageSharp.Processing.ResizeExtensions.Resize(IImageProcessingContext source, ResizeOptions options)
   at TexturePlugin.TextureEncoderDecoder.<>c__DisplayClass9_0.<Encode>b__0(IImageProcessingContext i)
   at TexturePlugin.TextureEncoderDecoder.Encode(Image`1 image, Int32 width, Int32 height, TextureFormat format, Int32 quality, Int32 mips)
   at TexturePlugin.TextureImportExport.Import(Image`1 image, TextureFormat format, Int32& width, Int32& height, Int32& mips, UInt32 platform, Byte[] platformBlob)
   at TexturePlugin.TextureImportExport.Import(String imagePath, TextureFormat format, Int32& width, Int32& height, Int32& mips, UInt32 platform, Byte[] platformBlob)
   at TexturePlugin.ImportTextureOption.ImportTextures(Window win, List`1 batchInfos)
   at TexturePlugin.ImportTextureOption.ExecutePlugin(Window win, AssetWorkspace workspace, List`1 selection)
   at UABEAvalonia.PluginWindow.BtnOk_Click(Object sender, RoutedEventArgs e) in D:\a\UABEA\UABEA\UABEAvalonia\PluginWindow.axaml.cs:line 53

**Comment by nesrak1** [comment]
The code that's having the exception is the mipmapping code trying to scale your image down to 0. However, there's a lot of checks to make sure the image you're importing can be mipmapped. Are you sure you don't actually have a 0x0 image you're importing?

**Comment by NikolasL015** [comment]
> The code that's having the exception is the mipmapping code trying to scale your image down to 0. However, there's a lot of checks to make sure the image you're importing can be mipmapped. Are you sure you don't actually have a 0x0 image you're importing?

I exported all the textures and modified some of them again, seems to work now. I think one of my old textures was bugged when I saved it in Photoshop.
But I have another issue: when I try to import more than 50 modified textures, the program freezes (not responding) forever, is it due to my CPU? (2,9 ghz, 6 cores and 12 threads)

**Comment by nesrak1** [comment]
It might just be taking a while. Encoding is definitely slower than decoding. The texture import/export doesn't have a progress bar, but it's probably a good idea to add one in a future update.

**Comment by NikolasL015** [comment]
> It might just be taking a while. Encoding is definitely slower than decoding. The texture import/export doesn't have a progress bar, but it's probably a good idea to add one in a future update.

I went to sleep to see if it was just slow, but it was still not responding when I woke up after 9 hours. (I've tried it many times.). Then I asked a friend of mine (who has a better CPU than mine) to try it, and he did it with 80 textures, but when he tried to import more than 100, the program froze too.

**Comment by nesrak1** [comment]
I'll have to make a big bundle to test on, but 9 hours definitely isn't right. Is it at max cpu the whole time? How big are the textures you're trying to import? I don't think the code could get stuck in a loop after importing too many textures.

**Comment by NikolasL015** [comment]
> I'll have to make a big bundle to test on, but 9 hours definitely isn't right. Is it at max cpu the whole time? How big are the textures you're trying to import? I don't think the code could get stuck in a loop after importing too many textures.

It uses the maximum CPU in just a fraction of time; all the textures were 512x512.
![image](https://github.com/nesrak1/UABEA/assets/119546725/b597446b-0b15-44ec-bb72-f15295723e54)

**Comment by nesrak1** [comment]
Can you check what texture format they are? I can't reproduce this with DXT5 images. Ten 2048x2048 images import in one second on my computer with a slightly worse CPU than the one in your screenshot.

**Comment by NikolasL015** [comment]
> Can you check what texture format they are? I can't reproduce this with DXT5 images. Ten 2048x2048 images import in one second on my computer with a slightly worse CPU than the one in your screenshot.

All of them are PNG. I managed to import ten 2048x2048 images too, but my problem is when I try to import more than 50–80.

PS: My 2048x2048 image imports took longer than yours, but it worked. (ten textures)
And it used the maximum CPU the whole time, unlike my previous screenshot.
![image](https://github.com/nesrak1/UABEA/assets/119546725/9eed0623-9815-4cfc-bbbd-6c2496c66bd3)

**Comment by nesrak1** [comment]
What texture format are the textures?

**Comment by NikolasL015** [comment]
> What texture format are the textures? Not like png, but like RGBA32 or DXT5. Single selecting a texture and clicking plugins -> edit texture will show this.

Oh sorry, all the textures are ASTC_RGB_8x8

**Comment by nesrak1** [comment]
@goodlord can you post the exact error message? Did you export the images with a different tool like AssetStudio or did you export with UABEA?

**Comment by goodlord** [comment]
`Plugin Batch import textures has crashed. Stacktrace:
System.InvalidOperationException: Target width 0 and height 0 must be greater than zero.
   at SixLabors.ImageSharp.Processing.Processors.Transforms.ResizeHelper.ThrowInvalid(String message)
   at SixLabors.ImageSharp.Processing.Processors.Transforms.ResizeHelper.CalculateTargetLocationAndBounds(Size sourceSize, ResizeOptions options)
   at SixLabors.ImageSharp.Processing.Processors.Transforms.ResizeProcessor..ctor(ResizeOptions options, Size sourceSize)
   at SixLabors.ImageSharp.Processing.ResizeExtensions.Resize(IImageProcessingContext source, ResizeOptions options)
   at SixLabors.ImageSharp.Processing.ResizeExtensions.Resize(IImageProcessingContext source, Int32 width, Int32 height, IResampler sampler, Rectangle targetRectangle, Boolean compand)
   at SixLabors.ImageSharp.Processing.ResizeExtensions.Resize(IImageProcessingContext source, Int32 width, Int32 height, IResampler sampler, Boolean compand)
   at SixLabors.ImageSharp.Processing.ResizeExtensions.Resize(IImageProcessingContext source, Int32 width, Int32 height)
   at TexturePlugin.TextureEncoderDecoder.<>c__DisplayClass9_0.<Encode>b__0(IImageProcessingContext i)
   at SixLabors.ImageSharp.Processing.ProcessingExtensions.Mutate[TPixel](Image`1 source, Configuration configuration, Action`1 operation)
   at TexturePlugin.TextureEncoderDecoder.Encode(Image`1 image, Int32 width, Int32 height, TextureFormat format, Int32 quality, Int32 mips)
   at TexturePlugin.TextureImportExport.Import(Image`1 image, TextureFormat format, Int32& width, Int32& height, Int32& mips, UInt32 platform, Byte[] platformBlob)
   at TexturePlugin.TextureImportExport.Import(String imagePath, TextureFormat format, Int32& width, Int32& height, Int32& mips, UInt32 platform, Byte[] platformBlob)
   at TexturePlugin.ImportTextureOption.ImportTextures(Window win, List`1 batchInfos)
   at TexturePlugin.ImportTextureOption.ExecutePlugin(Window win, AssetWorkspace workspace, List`1 selection)
   at UABEAvalonia.PluginWindow.BtnOk_Click(Object sender, RoutedEventArgs e) in D:\a\UABEA\UABEA\UABEAvalonia\Forms\PluginWindow.axaml.cs:line 53`

I exported with UABEA 
I resized using a plugin in GIMP and made them 50% width and 50% length.  The original image sizes were all 4096x4096 the  resized images are all 2048x2048.

**Comment by nesrak1** [comment]
Please try on the latest nightly. I didn't realize I had already made a fix for this bug but only applied it to the edit window and not batch import.

**Comment by goodlord** [comment]
I'll try that thanks!

edit:  That worked. Thanks again!
