### ISSUE TITLE
Error when load the texture

### ISSUE THREAD

**Issue by SalieriVerthandi** [nesrak1/UABEA#349]
there some error when i trying to load the texture. i don't know what happend.

Failed to encode texture format ASTC_RGB_5x5!
System.DllNotFoundException: Unable to load DLL 'textoolwrap' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at TexturePlugin.PInvoke.EncodeByPVRTexLib(IntPtr data, IntPtr buf, Int32 mode, Int32 level, UInt32 width, UInt32 height)
   at TexturePlugin.TextureEncoderDecoder.EncodePVRTexLib(Byte[] data, Int32 width, Int32 height, TextureFormat format, Int32 quality)
   at TexturePlugin.TextureEncoderDecoder.EncodeMip(Byte[] data, Int32 width, Int32 height, TextureFormat format, Int32 quality, Int32 mips)
   at TexturePlugin.TextureEncoderDecoder.Encode(Image`1 image, Int32 width, Int32 height, TextureFormat format, Int32 quality, Int32 mips)
   at TexturePlugin.TextureImportExport.Import(Image`1 image, TextureFormat format, Int32& width, Int32& height, Int32& mips, UInt32 platform, Byte[] platformBlob)
   at TexturePlugin.EditDialog.BtnSave_Click(Object sender, RoutedEventArgs e)

**Comment by nesrak1** [comment]
Duplicate: https://github.com/nesrak1/UABEA/issues/218#issuecomment-1399592063
