### ISSUE TITLE
crash while open bundle file 

### ISSUE THREAD

**Issue by FourTest** [nesrak1/UABEA#358]
while i open a bundle file export by unity 2021.3.28f1, UABEA crash.

crash tip:

system.l0.EndofStreamException: Unable to read beyond the end
ot the stream
at System.l0.BinanyReader.InternalRead(nt32 numBytes)
at svstem.l0.BinarReader.ReadUint32
at AssetsTools.NET.AssetsFileReader.ReadUInt320
at AssetsTools.NET.AssetBundleBlockAndDirinfo.Read(AssetsFileReader reader)
at AssetsTools.NET.AssetBundleFile.UnpacklnfoOnlyO
at AssetsTools.NET.AssetBundleFile.Read(AssetsFileReader reader)
at AssetsTools.NET.Extra.BundleFilelnstance..ctor(Stream stream, String filePath
3oolean unpacklfPacked)
at AssetsTools.NET.Extra.AssetsManager.LoadBundleFile(Stream stream, String
ath, Boolean unpacklfPacked)
at AssetsTools.NET.Extra.AssetsManager.LoadBundleFile(FileStream stream,
Boolean unpacklfPacked)
at AssetsTools.NET.Extra.AssetsManager.LoadBundleFile(String path, Boolean
InpacklfPacked)
at UABEAvalonia.Mainwindow.OpenFiles(Stringl files) in
:\a\UABEA\UABEA\UABEAvalonia\Forms\MainWindow.axaml.cs:line 164
at System.Threading.Tasks.Task.<>c,<ThrowAsync>b 128 0(0biect state)
at Avalonia.Threading.sendOrPostCallbackDispatcherOperation.InvokeCore0
at Avalonia.Threading.DispatcherOperation.Execute0
at Avalonia.Threading.Dispatcher.Executelob(DispatcherOperation job)
at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean
romExplicitBackgroundProcessingcallback
at Avalonia.Threading.Dispatcher.Signaled0
at Avalonia.Win32.Win32Platform.WndProc(intPtr hWnd, Uint32 msg, intPtr
wParam, IntPtr lParam)
at Avalonia.Win32Interop.UnmanagedMethods.DispatchMessage(MsG8
pmsg)
at Avalonia.Win32.Win32Dispatcherlmpl.RunLoop(CancellationToken
ancellationToken)
at Avalonia.Threading.DispatcherFrame.Run(lControlledDispatcherlmpl impl)
at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken
ancellationToken)
at
Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.St
art(stringl args)
at
Avalonia.ClassicDesktopstyleApplicationLifetimeExtensions.StartwithClassicDeskt
opLifetime(AppBuilder builder, Stringl args, ShutdownMode shutdownMode)
at UABEAvalonia.Program.Main(stringl args) in
:a\UABEA\UABEA\UABEAvaloniaProgram.cs:line 53

**Comment by nesrak1** [comment]
Is that an OCR of the error message? 🤨 
Anyways, does this open in any other tool like AssetStudio, AssetRipper, etc?

**Comment by nesrak1** [comment]
Given this doesn't work in other tools, I'm going to believe this is an encrypted file, which is not something I can support.
