### ISSUE TITLE
error while saving

### ISSUE THREAD

**Issue by vxczyle** [nesrak1/UABEA#365]
There was a problem while writing the file:
System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.Strategies.BufferedFileStreamStrategy.Seek(Int64 offset, SeekOrigin origin)
   at System.IO.FileStream.set_Position(Int64 value)
   at AssetsTools.NET.AssetsFileReader.set_Position(Int64 value)
   at AssetsTools.NET.AssetsFile.Write(AssetsFileWriter writer, Int64 filePos, List`1 replacers, ClassDatabaseFile typeMeta)
   at UABEAvalonia.InfoWindow.SaveFile(Boolean saveAs) in D:\a\UABEA\UABEA\UABEAvalonia\Forms\InfoWindow.axaml.cs:line 575

**Comment by nesrak1** [comment]
Duplicate #265
