### ISSUE TITLE
Saving is not done properly.

### ISSUE THREAD

**Issue by Kafu-Yukimura** [nesrak1/UABEA#43]
I modified the (filename).book.dat file by pressing the Import Raw button and then clicked Save, but it leaves 42.3 MB of saved files and exits without any error messages.

**Comment by drongood12** [comment]
Saving actually works, but when you change, you need to save it into a separate new file, for some reason the existing file does not change

**Comment by nesrak1** [comment]
> I modified the (filename).book.dat file by pressing the Import Raw button and then clicked Save, but it leaves 42.3 MB of saved files and exits without any error messages.

What version of uabea are you using? Are you editing a bundle or an assets file? When you clicked save did it ask where to save the file or did it instantly crash? What do you mean by "it leaves 42.3 MB of saved files"?
Please send a crashlog (https://github.com/nesrak1/UABEA/wiki/Sending-a-crashlog)

**Comment by Kafu-Yukimura** [comment]
@nesrak1 It asked where to save it, and I specified a location to save it and saved it.
After that, the UABEA window closes without completing with no response.
After that, 42.3 MB of saved file was created.


The log is:
2021/06/04 	午後 01:45:33	.NET Runtime		1026		None

Application: UABEAvalonia.exe
CoreCLR Version: 5.0.521.16609
.NET Version: 5.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException: Non-negative number required. (Parameter 'count')
   at System.IO.BinaryReader.ReadBytes(Int32 count)
   at AssetsTools.NET.AssetBundleFile.Write(AssetsFileWriter writer, List`1 replacers, ClassDatabaseFile typeMeta)
   at UABEAvalonia.MainWindow.SaveBundle(BundleFileInstance bundleInst, String path) in C:\Users\nesquack\Documents\GitRepos\UABEA\UABEAvalonia\MainWindow.axaml.cs:line 280
   at UABEAvalonia.MainWindow.AskForSaveLocation() in C:\Users\nesquack\Documents\GitRepos\UABEA\UABEAvalonia\MainWindow.axaml.cs:line 174
   at UABEAvalonia.MainWindow.MenuSave_Click(Object sender, RoutedEventArgs e) in C:\Users\nesquack\Documents\GitRepos\UABEA\UABEAvalonia\MainWindow.axaml.cs:line 153
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 157
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 107
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 134
   at UABEAvalonia.Program.Main(String[] args) in C:\Users\nesquack\Documents\GitRepos\UABEA\UABEAvalonia\Program.cs:line 47

**Comment by nesrak1** [comment]
Are you using release 2? I doubt it will fix anything but can you try using the [latest build](https://nightly.link/nesrak1/UABEA/workflows/dotnet-desktop/master/uabea-windows.zip)?

**Comment by Kafu-Yukimura** [comment]
This is the result occurred after using Release 2.

**Comment by nesrak1** [comment]
I understand that from the log but can you try on the latest build as well? You may be reporting a bug that has already been fixed.

**Comment by Kafu-Yukimura** [comment]
Same result as using Release 2 when using latest build...

The Unity version I'm working on right now is:
File version is 2019.4.13.34615, Product version is 2019.4.13.5343031

The log is:
2021/06/06 午後 07:15:05 .NET Runtime 1026 None

Application: UABEAvalonia.exe
CoreCLR Version: 5.0.521.16609
.NET Version: 5.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException: Non-negative number required. (Parameter 'count')
   at System.IO.BinaryReader.ReadBytes(Int32 count)
   at AssetsTools.NET.AssetBundleFile.Write(AssetsFileWriter writer, List`1 replacers, ClassDatabaseFile typeMeta)
   at UABEAvalonia.MainWindow.SaveBundle(BundleFileInstance bundleInst, String path) in D:\a\UABEA\UABEA\UABEAvalonia\MainWindow.axaml.cs:line 542
   at UABEAvalonia.MainWindow.AskForLocationAndSave() in D:\a\UABEA\UABEA\UABEAvalonia\MainWindow.axaml.cs:line 383
   at UABEAvalonia.MainWindow.MenuSave_Click(Object sender, RoutedEventArgs e) in D:\a\UABEA\UABEA\UABEAvalonia\MainWindow.axaml.cs:line 159
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 157
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 107
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 134
   at UABEAvalonia.Program.Main(String[] args) in D:\a\UABEA\UABEA\UABEAvalonia\Program.cs:line 47

**Comment by nesrak1** [comment]
What size is the bundle you're editing?

**Comment by Kafu-Yukimura** [comment]
The file of unity3d is 1.12 GB.
If you include resource and sharedassets0, it's about 2GB.

**Comment by Totsui** [comment]
I have that same issue with a4go bundle. I could send it to you if you need it for tests

**Comment by nesrak1** [comment]
@Totsui yes, that would help.

**Comment by Totsui** [comment]
@nesrak1 here is the compressed bundle in a zip file. Thanks for your help, and thanks for giving a new life to UABE btw.
DL link : https://www.mediafire.com/file/hhbuw3kqznj0jtp/defaultlocalgroup_assets_all_1561fb1f104c6135f864a5803791db15.zip/file

**Comment by nesrak1** [comment]
Sorry for the late reply. Probably related to #40 (was fixed, but library was not updated at this time). You should be able to load and save this file. Compression will be very, very slow (at least when selecting lzma). This is a problem with the c# lzma sdk being _very_ slow to compress. I could potentially use the c++ version instead but that would require a hack to the original writing code.

Let me know if it works for you now. I think @Kafu-Yukimura has the same problem, but I'm not 100%.

**Comment by Totsui** [comment]
Imma try when going home and i'll tell you, thanks a lot!

**Comment by Kafu-Yukimura** [comment]
@nesrak1 Even if I finally save, UABEA does not turn off and is saved well. Thanks for fixing it.
But Compress doesn't seem to be working properly yet.
If you open the data.unity3d file of about 1.14GB with UABEA and then compress it, the file size is 601MB. (lzma)
The event viewer log is not output separately.

**Comment by Kafu-Yukimura** [comment]
I try to compress in the latest build, the window closes.

The log is:
2021/07/31 午後 08:37:05 .NET Runtime 1026 なし

Application: UABEAvalonia.exe
CoreCLR Version: 5.0.721.25508
.NET Version: 5.0.7
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException: Non-negative number required. (Parameter 'count')
   at System.IO.BinaryReader.ReadBytes(Int32 count)
   at AssetsTools.NET.AssetBundleFile.Pack(AssetsFileReader reader, AssetsFileWriter writer, AssetBundleCompressionType compType)
   at UABEAvalonia.MainWindow.CompressBundle(BundleFileInstance bundleInst, String path, AssetBundleCompressionType compType) in D:\a\UABEA\UABEA\UABEAvalonia\MainWindow.axaml.cs:line 662
   at UABEAvalonia.MainWindow.AskForLocationAndCompress() in D:\a\UABEA\UABEA\UABEAvalonia\MainWindow.axaml.cs:line 489
   at UABEAvalonia.MainWindow.MenuCompress_Click(Object sender, RoutedEventArgs e) in D:\a\UABEA\UABEA\UABEAvalonia\MainWindow.axaml.cs:line 201
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 157
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 107
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 134
   at UABEAvalonia.Program.Main(String[] args) in D:\a\UABEA\UABEA\UABEAvalonia\Program.cs:line 47

**Comment by nesrak1** [comment]
I think only the unpacker has support for files larger than 2gb (unpacked). When packing, it still seems to load the entire file into memory first which causes this crash.

**Comment by nesrak1** [comment]
Updated the dll, check if it saves correctly now.

**Comment by Kafu-Yukimura** [comment]
Currently, saving and compression are working normally, so I close this thread. To reopen, please do not open this thread and open it again please.
