### ISSUE TITLE
Batch Export doesn't appear to work in latest build

### ISSUE THREAD

**Issue by TheSingleOneYT** [nesrak1/UABEA#48]
I tried out the latest version, UABEA just crashes when attempting to export multiple assets. Not sure if you know about this.

**Comment by nesrak1** [comment]
Batch export for a plugin or batch export for raw/dump?

**Comment by TheSingleOneYT** [comment]
Plugin

**Comment by nesrak1** [comment]
Is it possible you tried to export a Font Texture in your batch export? Texture batch export is working fine for me otherwise.

**Comment by TheSingleOneYT** [comment]
Somewhat works. I attempted batch export and it successfully exported some assets before crashing. Sadly, it exported in a random order so I'm not 100% sure what it attempted to export before breaking.

**Comment by TheSingleOneYT** [comment]
Yes, Among Us, sharedassets1.assets.

Stack trace:
Exception Info: System.DllNotFoundException: Unable to load DLL 'textoolwrap' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at TexturePlugin.PInvoke.DecodeByPVRTexLib(IntPtr data, IntPtr buf, Int32 mode, UInt32 width, UInt32 height)
   at TexturePlugin.TextureEncoderDecoder.Decode(Byte[] data, Int32 width, Int32 height, TextureFormat format)
   at TexturePlugin.TextureImportExport.ExportPng(Byte[] encData, String file, Int32 width, Int32 height, TextureFormat format)
   at TexturePlugin.ExportTextureOption.BatchExport(Window win, AssetWorkspace workspace, List`1 selection)
   at TexturePlugin.ExportTextureOption.ExecutePlugin(Window win, AssetWorkspace workspace, List`1 selection)
   at UABEAvalonia.PluginWindow.BtnOk_Click(Object sender, RoutedEventArgs e) in D:\a\UABEA\UABEA\UABEAvalonia\PluginWindow.axaml.cs:line 59
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 157
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 107
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 134
   at UABEAvalonia.Program.Main(String[] args) in D:\a\UABEA\UABEA\UABEAvalonia\Program.cs:line 47

**Comment by nesrak1** [comment]
Definitely not a batch export problem. I assume you were exporting only single dxt textures (these are decoded from c#) but the rest are decoded from c++. Try installing the c++ redistributable from here https://aka.ms/vs/16/release/vc_redist.x64.exe.

**Comment by TheSingleOneYT** [comment]
Yeah that worked, thanks!
