### ISSUE TITLE
Please support unity game version 2020.3

### ISSUE THREAD

**Issue by cacarasa** [nesrak1/UABEA#62]
i open files and nothing happens..

Thanks

**Comment by nesrak1** [comment]
If nothing happens (not even a crash) then it's not a supported file (assets file or bundle) and won't open.

**Comment by TheSingleOneYT** [comment]
I believe the latest version of Among Us is 2020.3.
I attempted to open it and it just crashes:
Application: UABEAvalonia.exe
CoreCLR Version: 5.0.721.25508
.NET Version: 5.0.7
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at AssetsTools.NET.Extra.AssetHelper.FindAssetClassByID(ClassDatabaseFile cldb, UInt32 id)
   at UABEAvalonia.InfoWindow.MakeDataGridItems() in C:\Users\nesquack\Documents\GitRepos\UABEA\UABEAvalonia\InfoWindow.axaml.cs:line 368
   at UABEAvalonia.InfoWindow..ctor(AssetsManager assetsManager, AssetsFileInstance assetsFile, String name, Boolean fromBundle) in C:\Users\nesquack\Documents\GitRepos\UABEA\UABEAvalonia\InfoWindow.axaml.cs:line 99
   at UABEAvalonia.MainWindow.MenuOpen_Click(Object sender, RoutedEventArgs e) in C:\Users\nesquack\Documents\GitRepos\UABEA\UABEAvalonia\MainWindow.axaml.cs:line 124
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run() in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 166
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 208
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 157
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 107
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 134
   at UABEAvalonia.Program.Main(String[] args) in C:\Users\nesquack\Documents\GitRepos\UABEA\UABEAvalonia\Program.cs:line 47

**Comment by nesrak1** [comment]
@TheSingleOneYT please make a separate issue for this

**Comment by TheSingleOneYT** [comment]
Ok

**Comment by nesrak1** [comment]
No further info, so closing.
