### ISSUE TITLE
Some MonoBehaviours fail to decode

### ISSUE THREAD

**Issue by mskgroup** [nesrak1/UABEA#69]
Application: UABEAvalonia.exe
CoreCLR Version: 5.0.421.11614
.NET Version: 5.0.4
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at UABEAvalonia.AssetImportExport.RecurseTextDump(AssetTypeValueField field, Int32 depth) in E:\UABES\UABEA\UABEAvalonia\AssetImportExport.cs:line 40
   at UABEAvalonia.AssetImportExport.DumpTextAsset(StreamWriter sw, AssetTypeValueField baseField) in E:\UABES\UABEA\UABEAvalonia\AssetImportExport.cs:line 35
   at UABEAvalonia.InfoWindow.SingleExportDump(List`1 selection) in E:\UABES\UABEA\UABEAvalonia\InfoWindow.axaml.cs:line 521
   at UABEAvalonia.InfoWindow.BtnExportDump_Click(Object sender, RoutedEventArgs e) in E:\UABES\UABEA\UABEAvalonia\InfoWindow.axaml.cs:line 255
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 157
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 116
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 148
   at UABEAvalonia.Program.Main(String[] args) in E:\UABES\UABEA\UABEAvalonia\Program.cs:line 47

事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-06-29T01:37:22.9669788Z" />
    <EventRecordID>22155</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>LAPTOP-9KQF6ISM</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: UABEAvalonia.exe
CoreCLR Version: 5.0.421.11614
.NET Version: 5.0.4
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at UABEAvalonia.AssetImportExport.RecurseTextDump(AssetTypeValueField field, Int32 depth) in E:\UABES\UABEA\UABEAvalonia\AssetImportExport.cs:line 40
   at UABEAvalonia.AssetImportExport.DumpTextAsset(StreamWriter sw, AssetTypeValueField baseField) in E:\UABES\UABEA\UABEAvalonia\AssetImportExport.cs:line 35
   at UABEAvalonia.InfoWindow.SingleExportDump(List`1 selection) in E:\UABES\UABEA\UABEAvalonia\InfoWindow.axaml.cs:line 521
   at UABEAvalonia.InfoWindow.BtnExportDump_Click(Object sender, RoutedEventArgs e) in E:\UABES\UABEA\UABEAvalonia\InfoWindow.axaml.cs:line 255
   at System.Threading.Tasks.Task.&lt;&gt;c.&lt;ThrowAsync&gt;b__140_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.&lt;&gt;c__DisplayClass5_0.&lt;Post&gt;b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG&amp; lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 157
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 116
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 148
   at UABEAvalonia.Program.Main(String[] args) in E:\UABES\UABEA\UABEAvalonia\Program.cs:line 47
</Data>
  </EventData>
</Event>

**Comment by mskgroup** [comment]
Application: UABEAvalonia.exe
CoreCLR Version: 5.0.721.25508
.NET Version: 5.0.7
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\ASUS\Desktop\aaas\TextMeshPro\Sprite-sharedassets0.assets-175.txt'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at UABEAvalonia.InfoWindow.BatchExportDump(List`1 selection) in E:\UABES\UABEA\UABEAvalonia\InfoWindow.axaml.cs:line 476
   at UABEAvalonia.InfoWindow.BtnExportDump_Click(Object sender, RoutedEventArgs e) in E:\UABES\UABEA\UABEAvalonia\InfoWindow.axaml.cs:line 253
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 157
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 116
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 148
   at UABEAvalonia.Program.Main(String[] args) in E:\UABES\UABEA\UABEAvalonia\Program.cs:line 47

**Comment by nesrak1** [comment]
Does this happen on a specific asset or all assets in a specific file?

**Comment by mskgroup** [comment]
Application: UABEAvalonia.exe
CoreCLR Version: 5.0.721.25508
.NET Version: 5.0.7
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at AssetsTools.NET.AssetsFileReader.ReadInt32() in E:\UABES\AssetsTools.NET\AssetTools.NET\Standard\AssetsFileFormat\AssetsFileReader.cs:line 47
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField) in E:\UABES\AssetsTools.NET\AssetTools.NET\Standard\AssetTypeClass\AssetTypeTemplateField.cs:line 153
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField) in E:\UABES\AssetsTools.NET\AssetTools.NET\Standard\AssetTypeClass\AssetTypeTemplateField.cs:line 209
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField) in E:\UABES\AssetsTools.NET\AssetTools.NET\Standard\AssetTypeClass\AssetTypeTemplateField.cs:line 209
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField) in E:\UABES\AssetsTools.NET\AssetTools.NET\Standard\AssetTypeClass\AssetTypeTemplateField.cs:line 209
   at AssetsTools.NET.AssetTypeInstance..ctor(AssetTypeTemplateField[] baseFields, AssetsFileReader reader, Int64 filePos) in E:\UABES\AssetsTools.NET\AssetTools.NET\Standard\AssetTypeClass\AssetTypeInstance.cs:line 16
   at AssetsTools.NET.AssetTypeInstance..ctor(AssetTypeTemplateField baseField, AssetsFileReader reader, Int64 filePos) in E:\UABES\AssetsTools.NET\AssetTools.NET\Standard\AssetTypeClass\AssetTypeInstance.cs:line 22
   at UABEAvalonia.AssetWorkspace.GetConcatMonoBaseField(AssetContainer cont, String managedPath) in E:\UABES\UABEA\UABEAvalonia\AssetWorkspace.cs:line 259
   at UABEAvalonia.AssetWorkspace.GetBaseField(AssetContainer cont) in E:\UABES\UABEA\UABEAvalonia\AssetWorkspace.cs:line 197
   at UABEAvalonia.InfoWindow.BatchExportDump(List`1 selection) in E:\UABES\UABEA\UABEAvalonia\InfoWindow.axaml.cs:line 479
   at UABEAvalonia.InfoWindow.BtnExportDump_Click(Object sender, RoutedEventArgs e) in E:\UABES\UABEA\UABEAvalonia\InfoWindow.axaml.cs:line 253
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 157
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 116
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 148
   at UABEAvalonia.Program.Main(String[] args) in E:\UABES\UABEA\UABEAvalonia\Program.cs:line 47
[Unnamed asset-resources.assets-85247.zip](https://github.com/nesrak1/UABEA/files/6759190/Unnamed.asset-resources.assets-85247.zip)

**Comment by nesrak1** [comment]
> This is the raw file of the asset：

Just the raw asset does not have all the info to debug this (type tree, file version, asset type, etc.) A full file would be preferred.

**Comment by mskgroup** [comment]
game download:https://cowtransfer.com/s/aaab1000b72142

error:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-07-04T01:42:57.5701146Z" />
    <EventRecordID>22736</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>LAPTOP-9KQF6ISM</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: UABEAvalonia.exe
CoreCLR Version: 5.0.421.11614
.NET Version: 5.0.4
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at UABEAvalonia.AssetImportExport.RecurseTextDump(AssetTypeValueField field, Int32 depth) in D:\a\UABEA\UABEA\UABEAvalonia\AssetImportExport.cs:line 40
   at UABEAvalonia.AssetImportExport.DumpTextAsset(StreamWriter sw, AssetTypeValueField baseField) in D:\a\UABEA\UABEA\UABEAvalonia\AssetImportExport.cs:line 35
   at UABEAvalonia.InfoWindow.SingleExportDump(List`1 selection) in D:\a\UABEA\UABEA\UABEAvalonia\InfoWindow.axaml.cs:line 521
   at UABEAvalonia.InfoWindow.BtnExportDump_Click(Object sender, RoutedEventArgs e) in D:\a\UABEA\UABEA\UABEAvalonia\InfoWindow.axaml.cs:line 255
   at System.Threading.Tasks.Task.&lt;&gt;c.&lt;ThrowAsync&gt;b__140_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.&lt;&gt;c__DisplayClass5_0.&lt;Post&gt;b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG&amp; lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 157
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 107
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 134
   at UABEAvalonia.Program.Main(String[] args) in D:\a\UABEA\UABEA\UABEAvalonia\Program.cs:line 47
</Data>
  </EventData>
</Event>

and

<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-07-04T01:42:58.0992355Z" />
    <EventRecordID>22737</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>LAPTOP-9KQF6ISM</Computer>
    <Security />
  </System>
  <EventData>
    <Data>UABEAvalonia.exe</Data>
    <Data>1.0.0.0</Data>
    <Data>609308e7</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.19041.804</Data>
    <Data>0e9c5eae</Data>
    <Data>e0434352</Data>
    <Data>000000000002d759</Data>
    <Data>967a0</Data>
    <Data>01d77075be2cd6e1</Data>
    <Data>C:\Users\Desktop\65.0\UABEAvalonia.exe</Data>
    <Data>C:\Windows\System32\KERNELBASE.dll</Data>
    <Data>204a58f1-8b19-44fb-9a37-8d9254928121</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by mskgroup** [comment]
> > This is the raw file of the asset：
> 
> Just the raw asset does not have all the info to debug this (type tree, file version, asset type, etc.) A full file would be preferred.

the game is Tainted.Grail.Conquest.v1.01

**Comment by nesrak1** [comment]
> at UABEAvalonia.AssetWorkspace.GetConcatMonoBaseField

Looking closer at this looks like a monobehaviour decoding error, so all decoding comes from the game's (Assembly-CSharp).dll files. So it's possible I missed a case for a field in the specific script you're trying to read, but I can't tell without looking at the assembly.

**Comment by nesrak1** [comment]
Closing since this issue is pretty old.
