### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by mskgroup** [nesrak1/UABEA#74]
game download:https://cowtransfer.com/s/aaab1000b72142

error:

1026
0
2
0
0
0x80000000000000

22736

Application
LAPTOP-9KQF6ISM

Application: UABEAvalonia.exe
CoreCLR Version: 5.0.421.11614
.NET Version: 5.0.4
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
at UABEAvalonia.AssetImportExport.RecurseTextDump(AssetTypeValueField field, Int32 depth) in D:\a\UABEA\UABEA\UABEAvalonia\AssetImportExport.cs:line 40
at UABEAvalonia.AssetImportExport.DumpTextAsset(StreamWriter sw, AssetTypeValueField baseField) in D:\a\UABEA\UABEA\UABEAvalonia\AssetImportExport.cs:line 35
at UABEAvalonia.InfoWindow.SingleExportDump(List1 selection) in D:\a\UABEA\UABEA\UABEAvalonia\InfoWindow.axaml.cs:line 521 at UABEAvalonia.InfoWindow.BtnExportDump_Click(Object sender, RoutedEventArgs e) in D:\a\UABEA\UABEA\UABEAvalonia\InfoWindow.axaml.cs:line 255 at System.Threading.Tasks.Task.&lt;&gt;c.&lt;ThrowAsync&gt;b__140_0(Object state) at Avalonia.Threading.AvaloniaSynchronizationContext.&lt;&gt;c__DisplayClass5_0.&lt;Post&gt;b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33 at Avalonia.Threading.JobRunner.RunJobs(Nullable1 priority) in //src/Avalonia.Base/Threading/JobRunner.cs:line 37
at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in //src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in //src/Windows/Avalonia.Win32/Win32Platform.cs:line 157
at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in //src/Avalonia.Base/Threading/Dispatcher.cs:line 61
at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in //src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 107
at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in //src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 134
at UABEAvalonia.Program.Main(String[] args) in D:\a\UABEA\UABEA\UABEAvalonia\Program.cs:line 47

and

1000 0 2 100 0 0x80000000000000 22737 Application LAPTOP-9KQF6ISM UABEAvalonia.exe 1.0.0.0 609308e7 KERNELBASE.dll 10.0.19041.804 0e9c5eae e0434352 000000000002d759 967a0 01d77075be2cd6e1 C:\Users\Desktop\65.0\UABEAvalonia.exe C:\Windows\System32\KERNELBASE.dll 204a58f1-8b19-44fb-9a37-8d9254928121

**Comment by nesrak1** [comment]
What type is this asset and what version is the game? Is it a bundle or an assets file?

**Comment by mskgroup** [comment]
it's monobehaviour、bundle

**Comment by nesrak1** [comment]
Can you click view data on this asset without it crashing?
