### ISSUE TITLE
Program crashes when attempting to view data of injected dump file

### ISSUE THREAD

**Issue by SorcererPonse** [nesrak1/UABEA#87]
I've been trying my hand at this for some time, but it seems like the program is inconsistent with handling importing files to replace certain assets, in this case AnimationClips with AnimationClip dumps. Before replacing the file, the data of the clip can be viewed just fine, the same also applies to the clip that is replacing the original one, but when the new one is injected into the original, attempting the view the data will cause the program the crash every time. This is consistent and I can upload the two resources.assets that I am trying to modify belonging to the game VRAST!, the original and the modified one if necessary. It doesn't matter if the data within the .txt is modified in a separate editor or not, and I am using the most recent Nightly build to attempt this. The application's Unity version is 2019.4.16 
Crash log is here:

Application: UABEAvalonia.exe
CoreCLR Version: 5.0.721.25508
.NET Version: 5.0.7
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at System.IO.BinaryReader.ReadInt32()
   at AssetsTools.NET.AssetsFileReader.ReadInt32()
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField)
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField)
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField)
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField)
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField)
   at AssetsTools.NET.AssetTypeTemplateField.MakeValue(AssetsFileReader reader)
   at AssetsTools.NET.AssetTypeInstance..ctor(AssetTypeTemplateField[] baseFields, AssetsFileReader reader, Int64 filePos)
   at AssetsTools.NET.AssetTypeInstance..ctor(AssetTypeTemplateField baseField, AssetsFileReader reader, Int64 filePos)
   at UABEAvalonia.AssetWorkspace.GetAssetContainer(AssetsFileInstance fileInst, Int32 fileId, Int64 pathId, Boolean onlyInfo) in D:\a\UABEA\UABEA\UABEAvalonia\AssetWorkspace.cs:line 161
   at UABEAvalonia.AssetWorkspace.GetBaseField(AssetContainer cont) in D:\a\UABEA\UABEA\UABEAvalonia\AssetWorkspace.cs:line 205
   at UABEAvalonia.DataWindow..ctor(AssetWorkspace workspace, AssetContainer cont) in D:\a\UABEA\UABEA\UABEAvalonia\DataWindow.axaml.cs:line 34
   at UABEAvalonia.InfoWindow.BtnViewData_Click(Object sender, RoutedEventArgs e) in D:\a\UABEA\UABEA\UABEAvalonia\InfoWindow.axaml.cs:line 241
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 157
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 107
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 134
   at UABEAvalonia.Program.Main(String[] args) in D:\a\UABEA\UABEA\UABEAvalonia\Program.cs:line 47

EDIT: I should also note that, when this happens, the game will also crash when attempting to load the AnimationClip that has been modified by UABEA.

**Comment by nesrak1** [comment]
Can you export dump the animation clip and import it back it without issues? It could be something like you edited an array but didn't change the size.

**Comment by SorcererPonse** [comment]
Yes, this applies to both the animation I am attempting to replace the original with and the original animation. However, even if I don't edit the new animation and try inserting the dump into the original animation, the same result still occurs. I did try modifying the new animation before to fit in with the old animation, but the program did not accept it when the values were incorrect. 

It's strange because I've used this same animation with a game on an older version of Unity (2017.1.5) and imported it via UABE without any issues whatsoever despite the differences in size and arrays. I only have issues when attempting to use this new animation to replace the original in this version of Unity. I'll try and see if I can import the animation from the original FBX file while using the right version of Unity to see if it'll work properly, but as of right now it doesn't. I've even extracted the original animations with uTinyRipper and tried modifying them but those dumps also cause crashes in the same manner.

**Comment by nesrak1** [comment]
Can you send just a dump of the AnimationClip? I haven't had this problem yet.

> It's strange because I've used this same animation with a game on an older version of Unity (2017.1.5) and imported it via UABE without any issues whatsoever despite the differences in size and arrays.

UABEA is a rewrite of UABE since I don't have the code to UABE. I've tried to match the format but sometimes I miss things.

**Comment by SorcererPonse** [comment]
Actually, I figured out the issue. I was using the wrong version of Unity the entire time, using the correct version works just fine. I would suggest that, if there's a way to tell, to possibly add a feature that notifies the user if a file is the incorrect version. But thank you for your quick responses, it was very helpful in the end!
