### ISSUE TITLE
crashes while opening file

### ISSUE THREAD

**Issue by postredaction** [nesrak1/UABEA#92]
program stopped responding after trying to open resources.assets. game is people playground

**Comment by nesrak1** [comment]
https://github.com/nesrak1/UABEA/wiki/Sending-a-crashlog

**Comment by FlameCaro** [comment]
I have the same issue. Event viewer says:

Application: UABEAvalonia.exe
CoreCLR Version: 5.0.921.35908
.NET Version: 5.0.9
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at AssetsTools.NET.Extra.AssetHelper.FindAssetClassByID(ClassDatabaseFile cldb, UInt32 id) in C:\Users\nesquack\Documents\GitReposLocal\AssetsTools.NET\AssetTools.NET\Extra\AssetHelper.cs:line 28
   at UABEAvalonia.InfoWindow.MakeDataGridItems() in C:\Users\nesquack\source\repos\UABEAvalonia\UABEAvalonia\InfoWindow.axaml.cs:line 350
   at UABEAvalonia.InfoWindow..ctor(AssetsManager assetsManager, AssetsFileInstance assetsFile, String name, Boolean fromBundle) in C:\Users\nesquack\source\repos\UABEAvalonia\UABEAvalonia\InfoWindow.axaml.cs:line 89
   at UABEAvalonia.MainWindow.MenuOpen_Click(Object sender, RoutedEventArgs e) in C:\Users\nesquack\source\repos\UABEAvalonia\UABEAvalonia\MainWindow.axaml.cs:line 104
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run() in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 166
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 208
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 157
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 107
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 134
   at UABEAvalonia.Program.Main(String[] args) in C:\Users\nesquack\source\repos\UABEAvalonia\UABEAvalonia\Program.cs:line 13

**Comment by nesrak1** [comment]
Closing since this issue is pretty old.
