### ISSUE TITLE
Crashes when applying emip file

### ISSUE THREAD

**Issue by MmeCromatique** [nesrak1/UABEA#94]
.NET Runtime Error in Windows Logs:

`Application: UABEAvalonia.exe
CoreCLR Version: 5.0.721.25508
.NET Version: 5.0.7
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
   at System.IO.FileStream.ValidateReadWriteArgs(Byte[] array, Int32 offset, Int32 count)
   at System.IO.FileStream.Read(Byte[] array, Int32 offset, Int32 count)
   at AssetsTools.NET.AssetsReplacerFromStream.Write(AssetsFileWriter writer) in C:\Users\nesquack\Documents\GitReposLocal\AssetsTools.NET\AssetTools.NET\Standard\AssetsReplacer\AssetsReplacerFromStream.cs:line 111
   at UABEAvalonia.AssetWorkspace.AddReplacer(AssetsFileInstance forFile, AssetsReplacer replacer, Stream previewStream) in C:\Users\nesquack\Documents\GitRepos\uabequickfixes\UABEA\UABEAvalonia\AssetWorkspace.cs:line 65
   at UABEAvalonia.LoadModPackageDialog.BtnOk_Click(Object sender, RoutedEventArgs e) in C:\Users\nesquack\Documents\GitRepos\uabequickfixes\UABEA\UABEAvalonia\LoadModPackageDialog.axaml.cs:line 112
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 157
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 107
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 134
   at UABEAvalonia.Program.Main(String[] args) in C:\Users\nesquack\Documents\GitRepos\uabequickfixes\UABEA\UABEAvalonia\Program.cs:line 47`

**Comment by nesrak1** [comment]
Was this ever fixed? Don't close the issue if it hasn't been.

**Comment by MmeCromatique** [comment]
> Was this ever fixed? Don't close the issue if it hasn't been.

Ho sorry, it's just that it's stated to not work, so I thought that it was useless to leave it open since it's a known issue

**Comment by nesrak1** [comment]
This emip was made from UABEA, correct? If you can, can you send the emip (I don't need the original file). Would make debugging quicker.

> it's just that it's stated to not work

Yeah that's fine, just leave it open anyway so I can track when this is fixed.

**Comment by MmeCromatique** [comment]
[Armand Pog.zip](https://github.com/nesrak1/UABEA/files/7040600/Armand.Pog.zip) Newer

[Armand_Pog Old.zip](https://github.com/nesrak1/UABEA/files/7040612/Armand_Pog.Old.zip) Older 

Here is the emip file made with UABEA, the crash has chaged also, before it crashed when applied, now it's when I load the file, no other window appears

**Comment by nesrak1** [comment]
Bug was already fixed in AssetsTools but I've updated it here in UABEA. Let me know if it's working now.

**Comment by nesrak1** [comment]
No response but apparently I fixed this roughly a year and a half ago, so it's probably fine to close.
