### ISSUE TITLE
UABEA launches, then closes a second later (or freezes)

### ISSUE THREAD

**Issue by jmdenza** [nesrak1/UABEA#95]
Using current build (uabea_rel3_win_x64) on Windows 10 [NET 5.0 Desktop Runtime (v5.0.9)]. Issue also existed with previous UABEA build. No successful launches to date. Reinstalled .NET 5.0 (Repair option) prior to this report to rule that out. Outdated UABE 2.2 launches w/o issue.

Log 1 (Application Error):

Faulting application name: UABEAvalonia.exe, version: 1.0.0.0, time stamp: 0x609308e7
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1110, time stamp: 0x4809adf2
Exception code: 0xc000041d
Fault offset: 0x0000000000034ed9
Faulting process id: 0x15a8
Faulting application start time: 0x01d797fce9303520
Faulting application path: C:\uabea_rel3_win_x64\net5.0\UABEAvalonia.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 9e7960b0-dcfa-4e56-b462-f65d7fe894fe
Faulting package full name: 
Faulting package-relative application ID: 

Log 2 (Application Error):

Faulting application name: UABEAvalonia.exe, version: 1.0.0.0, time stamp: 0x609308e7
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1110, time stamp: 0x4809adf2
Exception code: 0xe0434352
Fault offset: 0x0000000000034ed9
Faulting process id: 0x15a8
Faulting application start time: 0x01d797fce9303520
Faulting application path: C:\uabea_rel3_win_x64\net5.0\UABEAvalonia.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 4adb91ad-2639-44ec-85d2-e65f67a1387c
Faulting package full name: 
Faulting package-relative application ID: 

Log 3 (.NET Runtime):

Application: UABEAvalonia.exe
CoreCLR Version: 5.0.921.35908
.NET Version: 5.0.9
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException: Invalid create info - no Canvas provided (Parameter 'createInfo')
   at Avalonia.Skia.DrawingContextImpl..ctor(CreateInfo createInfo, IDisposable[] disposables) in /_/src/Skia/Avalonia.Skia/DrawingContextImpl.cs:line 106
   at Avalonia.Skia.SkiaGpuRenderTarget.CreateDrawingContext(IVisualBrushRenderer visualBrushRenderer) in /_/src/Skia/Avalonia.Skia/Gpu/SkiaGpuRenderTarget.cs:line 29
   at Avalonia.Rendering.DeferredRenderer.EnsureDrawingContext(IDrawingContextImpl& context) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 598
   at Avalonia.Rendering.DeferredRenderer.UpdateRenderLayersAndConsumeSceneIfNeeded(IDrawingContextImpl& context, Boolean recursiveCall) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 355
   at Avalonia.Rendering.DeferredRenderer.Render(Boolean forceComposite) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 304
   at Avalonia.Rendering.DeferredRenderer.Paint(Rect rect) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 224
   at Avalonia.Controls.TopLevel.HandlePaint(Rect rect) in /_/src/Avalonia.Controls/TopLevel.cs:line 333
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs:line 358
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.WndProc.cs:line 30

Thank you in advance for any help or insight.

**Comment by nesrak1** [comment]
> Outdated UABE 2.2 launches w/o issue.

UABE uses Win32 so you probably won't have any issues with it.

> Exception Info: System.ArgumentException: Invalid create info - no Canvas provided 

This is Avalonia, not UABEA, although I've never seen this error before and couldn't found anything about it on the internet. Do you have any uncommon computer setup?

**Comment by jmdenza** [comment]
I resolved the problem this morning (obsessed over it, really). A month ago I did a hard drive wipe and fresh install of Windows. It seems I've been on a standard account this entire time, and not Admin. Running the program on an Administrator account resolved all my issues! Something so simple! Thanks for your time, though. 
    On Monday, August 23, 2021, 07:47:53 AM CDT, nesrak1 ***@***.***> wrote:  
 
 



Outdated UABE 2.2 launches w/o issue.


UABE uses Win32 so you probably won't have any issues with it.


Exception Info: System.ArgumentException: Invalid create info - no Canvas provided


This is Avalonia, not UABEA, although I've never seen this error before and couldn't found anything about it on the internet. Do you have any uncommon computer setup?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
